### ISSUE TITLE
addEventListener doesn't reflect cmpApi.uiVisible being toggled

### ISSUE THREAD

**Issue by michael-sharethis** [InteractiveAdvertisingBureau/iabtcf-es#101]
**Version**
Which version does this occur on?

1.0.0-beta.18

**Module**
Is it core, cmpapi, cli, stub, or testing?

cmpapi

**Describe the bug**
A clear description of what the bug is.

After receiving the 'tcloaded' event I am toggling cmpApi.uiVisible with a custom command:

`{ showUI: (callback) => { cmpApi.uiVisible = true; } }` 

Nothing is received from the addEventListener callback after this happens. 

**Steps to Reproduce**

Load the stub, then the cmpapi. Fire an addEventListener command and then set the tcString field of the cmpapi. You will see the 'tcloaded' is fired. Finally, toggle a cmpApi.uiVisible = true. Notice that no event is fired.

**Expected behavior**
A clear description of what you expected to happen.

An event should be fired whenever cmpApi.uiVisible is toggled.

**Actual behavior**
A clear description of what happened that was not expected.

No event was fired when cmpApi.uiVisible is fired.

**Comment by michael-sharethis** [comment]
i've also noticed issues where the eventStatus field is set to "cmpuishown" even when i toggle cmpApi.uiVisible to false.

for instance, i have a custom command that initializes the cmp. it sets the tcstring and if there is no euconsent string it will toggle cmpApi.uiVisible to true. in this case "cmpuishown" should be trigged. but when euconsent cookies exist and cmpApi.uiVisible is set to false, "cmpuishown" should not be triggered.

**Comment by chrispaterson** [comment]
Thanks @michael-sharethis I'll look into it

**Comment by michael-sharethis** [comment]
thanks. 

also, it should be noted that if i execute `cmpApi.uiVisible = true;` before i execute `cmpApi.tcstring = 'mytcstring';`, I'll get the event status 'cmpuishown'. but if I reverse the order of these lines, i'll get the event status 'tcloaded'.

**Comment by chrispaterson** [comment]
@michael-sharethis setting uiVisible should not trigger an event.  Only when the tcModel (or tcString) is set on the CmpApi does the event trigger.

> i've also noticed issues where the eventStatus field is set to "cmpuishown" even when i toggle cmpApi.uiVisible to false.

I'm aware of this issue and have a fix for it

**Comment by michael-sharethis** [comment]
@chrispaterson thanks for the clarification!

**Comment by michael-sharethis** [comment]
@chrispaterson a few more things on this (i've upgraded to beta.19): 

1. after creating a cmpApi instance i'll set it's tcString and toggle uiVisible to true. the 'tcloaded' event will get called and not the 'cmpuishown' event. is this the desired behavior on your end?

2. once i update `cmpApi.tcString` and set `cmpApi.uiVisible = false`, the 'useractioncomplete' event is fired. this is the right behavior. however, once i update `cmpApi.tcString` and set `cmpApi.uiVisible = true`, the 'useractioncomplete' event is fired again... shouldn't the 'cmpuishown' event be fired there instead?
