### ISSUE TITLE
issue using Core

### ISSUE THREAD

**Issue by mikael-lundin** [InteractiveAdvertisingBureau/iabtcf-es#102]
**Version**
https://github.com/InteractiveAdvertisingBureau/iabtcf-es/tree/master/modules/core#iabtcfcore
After running the install  and provide the URL in the first example code I get an error saying that GLV is missin XMLhttprequest. I also try to create a new GVL object from a local JSON but it throws an error that says that it cannot create one from an empty or null object. Logging the json file before trying to create the GVL object works.

**Comment by chrispaterson** [comment]
> provide the URL in the first example code  I get an error saying that GLV is missin XMLhttprequest. 
Can you paste the error.
