### ISSUE TITLE
GVL baseUrl restrictions

### ISSUE THREAD

**Issue by mdurrant** [InteractiveAdvertisingBureau/iabtcf-es#103]
I can't find any information within the IAB TCF implementation guidelines that support the [restriction](https://github.com/InteractiveAdvertisingBureau/iabtcf-es/blob/master/modules/core/src/GVL.ts#L29-L67) on consensu.org being a valid base URL for the GVL. In fact, the section linked in the code suggests that browsers will respect the existing cache headers.

Do you have any insight into where this restriction is communicated? I'm worried that I've missed an important document.

**Comment by michael-sharethis** [comment]
maybe they're trying to reduce their costs by not having to host the GVL for everyone? although it does add an extra step for all the CMPs in pulling the latest GVL, versioning the old ones, and storing them somewhere :)

my main concern in regard to this is... how will we know when the GVL changes? we are planning on just querying the GVL from consensu at set intervals and if it changes automatically update our s3 bucket hosting our copy, but maybe there is some event hook we can listen to that will update us if there is a change?

@chrispaterson, do you know if there is an event we can listen for?

**Comment by chrispaterson** [comment]
There's no event, the vendor list is published every week https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20Consent%20string%20and%20vendor%20list%20formats%20v2.md#how-often-is-the-global-vendor-list-updated

**Comment by michael-sharethis** [comment]
@chrispaterson thank you!

**Comment by chrispaterson** [comment]
@mdurrant You haven't missed anything.  This has been a very important topic to IAB Europe but somehow it didn't come through clearly enough in the specification.  I'm working to get more clarification on this in the specification.
