### ISSUE TITLE
tcModel.gvl.changeLanguage() changes language code to uppercase and invalidates the url

### ISSUE THREAD

**Issue by tboneearls** [InteractiveAdvertisingBureau/iabtcf-es#104]
Given a baseUrl of `https://foo.com/v2/`

calling `tcModel.gvl.changeLanguage("de")` produces the url `https://foo.com/v2/purposes-DE.json` which results in a 403 error. Navigating to the default `https://vendorlist.consensu.org/v2/purposes-DE.json` throws a 403 as well.

Currently the only way to fix this is to transform this in our hosting, which is less than ideal.

Here's the function for reference. Removing line 374 should do the trick.
https://github.com/InteractiveAdvertisingBureau/iabtcf-es/blob/a9393ad/modules/core/src/GVL.ts#L372

Here's the w3c spec specifying case-sensitive URLs:
https://www.w3.org/TR/WD-html40-970708/htmlweb.html

**Comment by chrispaterson** [comment]
Thanks @tboneearls I'll fix this
