### ISSUE TITLE
Event Being Fired In Infinite Loop

### ISSUE THREAD

**Issue by michael-sharethis** [InteractiveAdvertisingBureau/iabtcf-es#107]
**Version**
Which version does this occur on?

1.0.0-beta.19

**Module**
Is it core, cmpapi, cli, stub, or testing?

cmpapi

**Describe the bug**
A clear description of what the bug is.

After running the stub, calling a custom command that sets the tcstring using a gvl passed from a GVL callback, and initializing the cmpapi from inside a GVL callback, events are fired in an infinite loop.

**This only happens if the cmpapi is created inside of the promise callback and uses the gvl passed through the promise.** 

**Steps to Reproduce**

`      

    import * as cmpstub from '@iabtcf/stub';
    import { CmpApi } from '@iabtcf/cmpapi';
    import { GVL, TCString, TCModel } from '@iabtcf/core';

    cmpstub();
    __tcfapi('init', 2, () => { }, {});

    GVL.baseUrl = 'https://sharethis-cmp-v2.s3.amazonaws.com';
    let gvl = new GVL('LATEST');
    gvl.readyPromise.then(() => {

      var cmpApi = new CmpApi(25, 1, {

        init: (callback, params) => {

          console.log('init');

          let model = new TCModel(gvl);
          model.cmpId = 25;
          model.cmpVersion = 1;
          model.consentScreen = 1;
          model.vendorListVersion = 27;

          let tc_string = TCString.encode(model);
          cmpApi.tcString = tc_string;

        }

      });

      cmpApi.tcModel = null;

    });

    __tcfapi('addEventListener', 2, (data) => {

      console.log(data);

    });
`

**Expected behavior**
A clear description of what you expected to happen.

Events shouldn't be called in an infinite loop

**Actual behavior**
A clear description of what happened that was not expected.

Events are called in an infinite loop

**Comment by michael-sharethis** [comment]
just an FYI, a workaround is getting the gvl in the init function...
`let gvl = await getGVL();`

**Comment by michael-sharethis** [comment]
this functionality is necessary because we need to combine the publisher tcString with the vendor tcString. in order to do this we need to create a tcString from a tcModel, and to do that we need a gvl. if we initialize the cmpapi before we have a gvl by setting the tcModel to null, commands that query for TCData will show that gdpr doesn't apply, which might not be true. it's fine for the CMP because we can implement logic to work around this, but vendors can't be expected to implement custom logic on a per CMP basis.

**Comment by chrispaterson** [comment]
Thanks @michael-sharethis – I'll look into it

**Comment by michael-sharethis** [comment]
@chrispaterson ty!

**Comment by chrispaterson** [comment]
@michael-sharethis Only set the TCModel when it's ready.  The way you're using this is not the intended way of using it.  I would order your code this way:

```javascript
import * as cmpstub from '@iabtcf/stub';
import { CmpApi } from '@iabtcf/cmpapi';
import { GVL, TCString, TCModel } from '@iabtcf/core';

cmpstub();

GVL.baseUrl = 'https://sharethis-cmp-v2.s3.amazonaws.com';

const model = new TCModel();
model.cmpId = 25;
model.cmpVersion = 1;
model.consentScreen = 1;
model.vendorListVersion = 27;

const cmpApi = new CmpApi(25, 1);
cmpApi.tcModel = model;
__tcfapi('addEventListener', 2, (data) => {

  console.log(data);

});
```
The `CmpApi` will handle getting the GVL and creating the `tcString`, you don't need to do any of that manually.  Setting  `tcModel` (or `tcString`) triggers the event to fire so you don't want to be setting a model or a string within a custom event.

Or if you really want to create the `tcString` you would do this:
```javascript
import * as cmpstub from '@iabtcf/stub';
import { CmpApi } from '@iabtcf/cmpapi';
import { GVL, TCString, TCModel } from '@iabtcf/core';

cmpstub();

GVL.baseUrl = 'https://sharethis-cmp-v2.s3.amazonaws.com';

const gvl = new GVL(27); // get vendor list version 27
const model = new TCModel(gvl);
model.cmpId = 25;
model.cmpVersion = 1;
model.consentScreen = 1;

const cmpApi = new CmpApi(25, 1);
cmpApi.tcModel = TCString.encode(model);

__tcfapi('addEventListener', 2, (data) => {

  console.log(data);

});
```

**Comment by michael-sharethis** [comment]
@chrispaterson the cmp won't be able to access the publisher tcString. the publisher tcString is being stored as a first party cookie. therefore the model that is being set is inaccurate.

**Comment by chrispaterson** [comment]
> the cmp won't be able to access the publisher tcString. the publisher tcString is being stored as a first party cookie.

Do you mean just the `publisherTC` segment or the encoded `tcString` is stored in a first-party cookie?  If the latter then the string should have the publisherTC segment attached to it if `isServiceSpecific` was set to `true` on the `TCModel` before `TCString.encode(tcModel)` was called.  In that case your code would look like:

```javascript
import * as cmpstub from '@iabtcf/stub';
import { CmpApi } from '@iabtcf/cmpapi';
import { TCString } from '@iabtcf/core';

function getCookie(name) {
  const re = new RegExp(name + "=([^;]+)")
  const value = re.exec(document.cookie);

  return (value != null) ? unescape(value[1]) : null;
}

cmpstub();

const cmpApi = new CmpApi(25, 1);

cmpApi.tcString = getCookie('euconsent-v2');

__tcfapi('addEventListener', 2, (data) => {

  console.log(data);

});
```

**Comment by michael-sharethis** [comment]
i mean the publisherTC segment is stored in a first part cookie under the publisher's domain. this seemed to make sense to me given that the publisherTC segment is publisher specific and shouldn't be stored under the consensu domain. maybe i'm missing something though?

**Comment by chrispaterson** [comment]
No you're right – your instinct is correct.  Depending on whether the whole TC string is "Globally-Scoped" (stored on consensu.org) or "Service Specific" (stored in a local cookie/ local storage) the library handles it differently.  In the case that it is "Service Specific", the Publisher TC is stored with the whole TC string.  But you are correct in noting that there is no way to use the `TCString` Class right now to just get the Publisher TC or to load them separately.  I'm working on a way to pass which segments to encode with an "EncodingOptions" object that would look something like this:

```javascript

const tcString = TCString.encode(tcModel, {
   segments: [
      'publisherTC'
    ]
});
```

Hopefully that'll solve your use case.  I just need to write some tests for it but you can see it on the develop branch.
https://github.com/InteractiveAdvertisingBureau/iabtcf-es/blob/develop/modules/core/src/TCString.ts#L68

https://github.com/InteractiveAdvertisingBureau/iabtcf-es/blob/develop/modules/core/src/encoder/EncodingOptions.ts

I'm hoping to release this today or tomorrow in the 1.0.0-beta.20 version
