### ISSUE TITLE
Vendor ranges incorrectly decoded from publisher restrictions

### ISSUE THREAD

**Issue by lukfed** [InteractiveAdvertisingBureau/iabtcf-es#112]
**Version**
1.0.0-beta.19

**Module**
core
Suspicious line causing an issue: https://github.com/InteractiveAdvertisingBureau/iabtcf-es/blob/master/modules/core/src/encoder/field/PurposeRestrictionVectorEncoder.ts#L124

**Describe the bug**
When the publisher restriction contains a range of vendors then the resulted list of vendors has extra entries.

**Steps to Reproduce**
1. Try decode a core string containing publisher restriction with a vendor range
2. List vendors using `TCModel.publisherRestrictions.getVendors()`

**Expected behavior**
The range 8-9 should be returned for core string: COwWHt-OwWHt-DNACOENAXCAANDAAEkAAAAAFpQBQABAAGgAQABIBXgFpAK_ABAK-ACCAAwAIAAk

**Actual behavior**
The range 8-16 is returned.

**Comment by chrispaterson** [comment]
Thanks @lukfed I'll look into this
