### ISSUE TITLE
XHR requests not working on IE11

### ISSUE THREAD

**Issue by nealrosen04** [InteractiveAdvertisingBureau/iabtcf-es#114]
**Version**
1.0.0-beta.19

**Module (core, cmpapi, cli, stub, or testing)**
core

**Describe the bug**
IE11 does not support "json" responseType.  This means that the response does not get automatically parsed, instead remaining in json string format.  I've tested the following fix in core/src/Json.ts locally and it works.
* remove the req.responseType check
* if req.response is a string, try to JSON.parse it.
* resolve the response
* Here's the modified code

`

          if (req.status >= 200 &&
            req.status < 300 &&
            req.response) {

            let response = req.response;
            if (typeof req.response === 'string') {
              try {
                response = JSON.parse(response);
              } catch (e) {}
            }
            resolve(response);

          } else {
`
**Steps to Reproduce**
Fetch a remote GVL on IE11

**Expected behavior**
GVL should download

**Actual behavior**
The logic in core/src/Json.ts rejects the response because req.responseType is not "json".  It is an empty string on IE11.

**Comment by chrispaterson** [comment]
thanks @nealrosen04, I think I had it this way before and changed it not realizing it would break IE11.  I used your code and it'll be in the next release.
