### ISSUE TITLE
TCString.encode writes all vendors as disclosed even after GVL.narrowVendorsTo([...])

### ISSUE THREAD

**Issue by matita** [InteractiveAdvertisingBureau/iabtcf-es#117]
**Version**
1.0.0-beta.20

**Module (core, cmpapi, cli, stub, or testing)**
core

**Describe the bug**
`TCString.encode` encodes the disclosed vendors segment with all the vendors in the GVL, while when invoking `tcModel.gvl.narrowVendorsTo([12, 100])` it should only show vendors `12` and `100` as disclosed.

**Steps to Reproduce**
Run this code:
```js
const tcModel = new TCModel(new GVL());
tcModel.cmpId = 123;
tcModel.cmpVersion = 1;

tcModel.gvl.readyPromise.then(() => {
  tcModel.gvl.narrowVendorsTo([12, 100]);
  tcModel.vendorsDisclosed.empty();
  tcModel.setAllVendorsDisclosed();
  console.log('original vendorsDisclosed', tcModel.vendorsDisclosed.size); // outputs 2

  const encoded = TCString.encode(tcModel);
  const decoded = TCString.decode(encoded);
  console.log('decoded vendorsDisclosed', decoded.vendorsDisclosed.size); // outputs 192  while it should output 2
});
```

**Expected behavior**
After encoding and decoding again `decoded.vendorsDisclosed` should contain only the originally narrowed vendors.

**Actual behavior**
After encoding and decoding again `decoded.vendorsDisclosed.size` contains all the vendors in the GVL.

**Comment by matita** [comment]
It actually seems like `GVL.clone()` does not take narrowed vendors into account:

```js
const gvl = new GVL();
gvl.readyPromise.then(() => {
  gvl.narrowVendorsTo([12, 100]);
  console.log('gvl narrowed vendors', Object.keys(gvl.vendors)); // outputs ['12', '100']
  const clonedGvl = gvl.clone();
  console.log('clonedGvl narrowed vendors', Object.keys(clonedGvl.vendors)); // outputs all the vendors in the gvl
});
```

**Comment by chrispaterson** [comment]
Thanks Matteo!  Good catch!  I'll work on this
