### ISSUE TITLE
Use of MaxVendorId of 0 to denote empty vendor consent set correct?

### ISSUE THREAD

**Issue by denis-angilella** [InteractiveAdvertisingBureau/iabtcf-es#121]
**Version**
1.0.0-beta.22 ? used through https://iabtcf.com/#/encode

**Module (core, cmpapi, cli, stub, or testing)**
code vendor consent encoder

**Describe the bug**
Vendor consent encoder use a max vendor ID of 0 to denote an empty consent set

Is this a correct behavior as per the TCF 2.0 specification or a bug?

**Steps to Reproduce**
Go to https://iabtcf.com/#/encode
Toggle "Is Service Specific"
Get generated TC string like `COwtZcVOwtZcVLwAAAENAdCgAAAAAAAAAAAAAAAAAAAA.YAAAAAAAAAAAAAAAAAA`
Decode first segment as URL-safe base64
Get MaxVendorID from bits 213 to 228: it is 0

**Expected behavior**
The [TCF 2.0 specification](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20Consent%20string%20and%20vendor%20list%20formats%20v2.md) doesn't mention that MaxVendorId of 0 can be used to denote an empty vendor consent set

There is no test in [VendorVectorEncoder.test.ts](https://github.com/InteractiveAdvertisingBureau/iabtcf-es/blob/master/modules/core/test/encoder/field/VendorVectorEncoder.test.ts) with an empty vector list as input

Please clarify how an empty vendor consent set should be encoded.

**Actual behavior**
`VendorVectorEncoder` encodes an empty `Vector` with a max ID of 0

**Comment by chrispaterson** [comment]
Both MaxVendorID and `IsRangeEncoding` bits must exist or else the segment does not exist.  So therefore if there are no vendors to encode the maximum encoded vendor with a positive consent value is 0.

**Comment by denis-angilella** [comment]
Thanks @chrispaterson for your quick reply.

So if I understand correctly, if there are no vendors to encode:
1. `MaxVendorID` is 0
2. `IsRangeEncoding` should be 0 to indicate a BitField section because this is the shorted representation
3. The corresponding BitField section should be of length `MaxVendorID` bits = 0, i.e. it isn't present

**Comment by chrispaterson** [comment]
Yes that's right. 
#2 is inconsequential it could be either `0` or `1` but something should be there to maintain the structure.
