### ISSUE TITLE
consentLanguage ignored

### ISSUE THREAD

**Issue by derdeka** [InteractiveAdvertisingBureau/iabtcf-es#122]
**Version**
1.0.0-beta.22

**Module (core, cmpapi, cli, stub, or testing)**
core

**Describe the bug**

changing consentLanguage has no effect to consent string

**Steps to Reproduce**

https://iabtcf.com/#/encode
switch consentLanguage

**Expected behavior**

consent string should reflect selected `consentLanguage`

**Actual behavior**

encoded `consentLanguage` is always `EN`

**Comment by vincent-ogury** [comment]
We also have spot this issue.

in TCString.ts instead of having:
```
    tcModel.consentLanguage = gvl.language;
```
May be we should:
```
if (!GVL.consentLanguages.has(tcModel.consentLanguage)) {
   tcModel.consentLanguage = 'EN'
}
```

This way we can directly setup the language with managing this in GVL.

In GVL I have to:
```
      const gvl = await get(version).then(g => g.clone())
      if (GVL.consentLanguages.has(uLanguage)) {
        if (!GVL.LANGUAGE_CACHE.has()) {
          GVL.LANGUAGE_CACHE.set(uLanguage, GVL.LANGUAGE_CACHE.get('EN'));
        }
        await gvl.changeLanguage(uLanguage);
      }
```
Or do that in the cache, and having X time the GVL in cache in memory. So not good.
