### ISSUE TITLE
Issue using __tcfapi and getting 'getTCData' response

### ISSUE THREAD

**Issue by IdanLanger** [InteractiveAdvertisingBureau/iabtcf-es#124]
The [documentation](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20CMP%20API%20v2.md#L182) states that:
> The callback shall be called immediately and without any asynchronous logic with whatever is available in the current state of the CMP.

However, when trying to call `getTCData` in the following way:
```js
__tcfapi('getTCData', 2, (tcData, success) => {
  if(success) {
    console.log('SUCCESS', { tcData })
  } else {
    console.log('ERROR')
  }
});
```

The callback is never invoked.
What am I doing wrong?

**Comment by chrispaterson** [comment]
Hi @IdanLanger, can you tell me more about your context?  Are you using the @iabtcf/cmpapi library?
