### ISSUE TITLE
Wrong decoding of custom purposes on IAB TCF Code Library and CMP Validator

### ISSUE THREAD

**Issue by tla-sirdata** [InteractiveAdvertisingBureau/iabtcf-es#125]
I've encoded a TCString including a PublisherTC segment with the following purposes:
- purpose 1 on consent
- purpose 5 on legitimate interest
- 2 custom purposes on consent
- 1 custom purpose on legitimate interest

Here is the TCString: `COwnRWbOwnRZLBcABBENAdCsAP_AAH_AAAqIF0EWSQgCYWghI0QUBxBAIYAfJgSCAMgCAAQIoSgFQISERBAGKiAQHAEQJAAAGBAAEACAAQAgHGBMCQAAgAABiRCEQUGICzNIBIBAggEaYUFAAAVmGkHCmZCY70ywOmQLoIIEBAEAkABAIAADECAQwAQDAAAAYAkAAABAhIKAAgIiAAEcAAAAAAgAAAAAAABAAAAAAAAAICIAAABAAAgAiAAAAAAGgIQAACBAAAAQIAAAAANAAAAiCEAQgoEAIgAA.cAAAAQAAAeI`

When encoding the TCString, I set the custom purposes fields as follows:
- NumCustomPurposes = `3`
- CustomPurposesConsent = `110`
- CustomPurposesLITransparency = `001`

Through the API, our CMP surfaces the TCData object as expected:
<img width="532" alt="getTCData" src="https://user-images.githubusercontent.com/38423751/77228240-35c34200-6b86-11ea-80f6-f9c68a1b78f6.png">

But when I decode the TCString in the [IAB TCF Code Library](https://iabtcf.com/?#/decode), the decoder doesn't split the custom purposes in consent and legitimate interest. Instead of decoding 3 consents and 3 legitimate interests, the decoder interprets 6 consents.
<img width="300" alt="iab-decoder" src="https://user-images.githubusercontent.com/38423751/77228313-ba15c500-6b86-11ea-9294-f758667d0172.png">

The same problem occurs in the CMP Validator:
<img width="568" alt="cmp-validator" src="https://user-images.githubusercontent.com/38423751/77228439-c2bacb00-6b87-11ea-96ce-472004c6639c.png">

I think both tools need to take in consideration the `NumCustomPurposes` field to split the purposes.

Thanks

**Comment by yogeshmuli** [comment]
@tla-sirdata How did you set consent for custom purposes

**Comment by tla-sirdata** [comment]
@yogeshmuli I've encoded a PublisherTC segment in the TCString as described [here](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20Consent%20string%20and%20vendor%20list%20formats%20v2.md#publisher-purposes-transparency-and-consent).
In my example, the encoded segment value is `cAAAAQAAAeI`

**Comment by yogeshmuli** [comment]
@tla-sirdata  thanks got it!!

**Comment by chrispaterson** [comment]
@tla-sirdata in the latest version of the library this encoding error should be addressed.  The issue is that you are defining custom purposes 1,2, and 6 – there is a gap in the sequence.  The `numCustomPurposes` was counting the actual number defined, not the maximum ID defined.  iabtcf.com was not aggregating legitimate interest and consents it was showing that no legitimate interests were set and 1,2, and 6 were set for consent.  I changed the site to only show positive values.

**Comment by tla-sirdata** [comment]
@chrispaterson I just tried the new version and now the `Publisher Custom Consents` section contains 1,2,6 but still no `Publisher Custom Legitimate Interest` section.
I was expecting to see 2 positive purposes for consent (1,2) and 1 positive purpose for LI (3).
I think it's a bit confusing that the `numCustomPurposes` is `3` but we present a signal for an id `6`.  

In the CMP validator, I'm having this now (the LI signal no longer appears)
<img width="500" alt="validator" src="https://user-images.githubusercontent.com/38423751/77823736-a1b12780-70fd-11ea-9b31-0cce3a7b2217.png">

Through the CMP API, I surface ids `from 1 to 3` and not `from 1 to 6` as there's only 3 custom purposes. Can you confirm that what I surface through the API is correct?

Thanks

**Comment by chrispaterson** [comment]
I need to see 

1. how you’re defining the custom purposes
2. How you’re setting the consents for them
3. How you’re setting the legitimate interests for them

**Comment by tla-sirdata** [comment]
1. I created a list of 3 custom purposes with a legal basis for each : consent for 1st and 2nd, LI for 3rd. Each purpose is given an id based on its position in the list. I come out with 3 ids : `1, 2, 3`
2. When encoding, I set `numCustomPurposes` with the list size : `3`
3. I set `customPurposesConsent` with `3` bits. The 2 first bits are `1`, the 3rd one is always `0` as it's not on consent
4. I also set `customPurposesLITransparency` with `3` bits. The 2 first bits are always `0` as they're not on LI, the 3rd one is `1`

**Comment by tla-sirdata** [comment]
Just wanna add information I found [here](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20Consent%20string%20and%20vendor%20list%20formats%20v2.md#publisher-purposes-transparency-and-consent) for custom purposes fields : 

`NumCustomPurposes`
Custom purpose IDs are numbered `1` to NumberCustomPurposes. Custom purposes will be defined by the publisher and displayed to a user in a CMP user interface.
If the publisher does not use any Custom Purposes, this field is set to `0` and the following two fields will be omitted.

`CustomPurposesConsent`
The consent value for each CustomPurposeId from `1` to `NumberCustomPurposes`

`CustomPurposesLITransparency`
The legitimate Interest disclosure establishment value for each CustomPurposeId from `1` to `NumberCustomPurposes`

So it's clear that we can't have a purpose id `6` in my case.

BTW there's a typo in the doc : it should be `NumCustomPurposes` instead of `NumberCustomPurposes`.

Thanks

**Comment by laurent-chriqui** [comment]
From what I have seen in the code:
`CustomPurposesConsent `and `CustomPurposesLITransparency `have a bitlength of 24 instead of `NumCustomPurposes`

I think there was a mistake in this fix: 
https://github.com/InteractiveAdvertisingBureau/iabtcf-es/issues/52

`publisherConsents` was mistaken with the two fields afore mentionned which should not have a fixed bitlength.

**Comment by chrispaterson** [comment]
Nice catch @laurent-chriqui, I had forgotten that those are viable length encodings.  I'll need to open a new issue to fix that.
