### ISSUE TITLE
vendor-list is incorrectly re-requested on __tcfapi.getVendorList call

### ISSUE THREAD

**Issue by PsychodelEKS** [InteractiveAdvertisingBureau/iabtcf-es#128]
**Version**
v1.0.0-beta.25

**Module (core, cmpapi, cli, stub, or testing)**
cmpapi

**Describe with reproduction steps – What is the expected behavior?**

Say we have a page with cmpapi, when new user visits it, we should instantiate it with some settings (cmpId, cmpVersion, vendor-list lang):
1. create GVL instance (with correct base url)
2. in gvlInstance.readyPromise setup correct lang with: ```gvlInstance.changeLanguage(lang)``` it downloads latest vendor-list.json (ver 30 for example) and corresponding purposes.json if needed
3. in gvlInstance.changeLanguage success promise callback create TCModel instance (with configured gvl from step 1, cmpId, cmpVersion, isServiceSpecific) and serialize it with `TCString.encode`
4. instantiate CMPAPI: ```CmpApi(cmpId, cmpVersion, true)``` (service-specific)
5. call ```cmpapiInstance.update``` with serialized value from step 3 and uiShown=true

so now we have API up and running, but if anyone calls `getVendorList` API command (say to render vendors list interface), the vendor list is re-requested with version specified in the serialized TC string (ver 30 which was the latest when GVL was created), and it is requested as archived version with `%BASEURL%/archives/vendor-list-v30.json``` url.
problems:
1. vendor-list is re-requested, though the version was already downloaded
2. vendor-list is re-requested through archives url, though it is requested for the latest version (we downloaded LATEST which was 30 and now we need to download ver 30 and request it as archived)
3. if GVL lang is set to any other from EN, it is ignored in getVendorList and EN version is returned anyway.

I think there must be an option to pass TCModel instance to the CmpApi.update method, as it was before with CmpApi.tcModel attribute, so it can be instantiated/updated with fully configured TCModel (with vendor-list available from the start)

**Comment by chrispaterson** [comment]
I think I can solve 1 & 2. 

3. if GVL lang is set to any other from EN, it is ignored in getVendorList and EN version is returned anyway.
    * the [`"getVendorList"`](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20CMP%20API%20v2.md#getvendorlist) method is not specified to do anything with language.  Language translations do not have a "vendors list" in them, they are just translations of the legal declarations.

**Comment by PsychodelEKS** [comment]
> * the [`"getVendorList"`](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20CMP%20API%20v2.md#getvendorlist) method is not specified to do anything with language.  Language translations do not have a "vendors list" in them, they are just translations of the legal declarations.

Prior to beta 21, when GVL was set to a TCModel and TCModel set to CmpApi, the vendor-list returned had translated purposes names/descriptions inside and it was good =)

**Comment by PsychodelEKS** [comment]
@chrispaterson 
so is it a total no-no with localized vendor-list in reference `getVendorList` implementation? `GVL.getJson` returns localized one btw. For my usage scenario I can expose `getJson`, but the desired behavior seems to be handy and does not violate any RFCs (as vendor-list.json is a legal source of EN translations for purposes/features).

**Comment by chrispaterson** [comment]
I don't believe it's a violation.  It's just something that is underspecified.

**Comment by sunandhaC** [comment]
@chrispaterson 
With release version 1.0.0, 
Issue - 2 :
"vendor-list is re-requested through archives url, though it is requested for the latest version (we downloaded LATEST which was 30 and now we need to download ver 30 and request it as archived)"

is still exists.

**Comment by chrispaterson** [comment]
@sunandhaC are the cmpapi and core libraries both on 1.0.0?  They need to both be for it to work.  Because if not, then the cmpapi will get a separate copy of the core library and the cache won't be shared.

I'm not quite sure I understand your problem.  Could you outline it in steps to reproduce?

**Comment by PsychodelEKS** [comment]
@chrispaterson 
@sunandhaC 
works fine for me on the latest v1.0.1-0
