### ISSUE TITLE
switching consentLanguage incorrectly loads translation files

### ISSUE THREAD

**Issue by derdeka** [InteractiveAdvertisingBureau/iabtcf-es#129]
**Version**
v1.0.0-beta.24

**Module (core, cmpapi, cli, stub, or testing)**
core

**Describe with reproduction steps – What is the expected behavior?**

When switching `consentLanguage` it incorrectly loads translation files.

E.g. when switching to `FR` on https://iabtcf.com/#/encode, it tries to load `https://iabtcf.com/vendorlist/purposes-FR.json` which does not exist.
Url should be `https://iabtcf.com/vendorlist/purposes-fr.json` (lowercase language).

**Comment by chrispaterson** [comment]
I know...  This is because I can't make an assumption that the language part of the file name is lowercase.   I think I'll make it so that the TCModel doesn't automatically load the language in the GVL.
