### ISSUE TITLE
[UI] Special Feature Optins isn't take into account

### ISSUE THREAD

**Issue by pribor** [InteractiveAdvertisingBureau/iabtcf-es#133]
UI: https://iabtcf.com/#/encode

Seems that UI doesn't take `Special Feature Optins` into account. If i choose any combination of fields the ecoded string remains the same and the collection is empty after decoding.

**Comment by chrispaterson** [comment]
Thank @pribor I upgraded the underlying library version and forgot that I had changed `specialFeatureOptIns` to `specialFeatureOptins` for https://github.com/InteractiveAdvertisingBureau/iabtcf-es/issues/98 

Should be fixed now
