### ISSUE TITLE
The Stack interface is wrong does not include specialFeatures field

### ISSUE THREAD

**Issue by carloslfu** [InteractiveAdvertisingBureau/iabtcf-es#134]
**Version**
v1.0.0-beta.26.

**Module (core, cmpapi, cli, stub, or testing)**
Core

**Describe with reproduction steps – What is the expected behavior?**
The [Stack interface](https://github.com/InteractiveAdvertisingBureau/iabtcf-es/blob/master/modules/core/src/model/gvl/Stack.ts#L3) does not include `specialFeatures ` field.

**Comment by chrispaterson** [comment]
Thanks Carlos!
