### ISSUE TITLE
Last triggered eventStatus should not repeat in addEventListener function.

### ISSUE THREAD

**Issue by nejcsever** [InteractiveAdvertisingBureau/iabtcf-es#137]
**Version**
1.0.0-beta.29

**Module (core, cmpapi, cli, stub, or testing)**
cmpapi, stub

**Describe with reproduction steps – What is the expected behavior?**
`addEventListener` function fires same `eventStatus` if called multiple times with the same `uiVisible` value. I think that the same `eventStatus` should not be triggered in succession. This issue relates to issue number #136 but I think it belongs into a separate bug report (it might be a fix for #136 ).

**Example 1 - Firing multiple cmpApi update with `uiVisible=false`:**
```
window.__tcfapi('addEventListener', 2, (tcData) => console.log(tcData.eventStatus));
let testTCString = "COeTFulOk0pYVBiAKDENAXCsABCAACmAACZYA3oOAIQAQCICAwIsguI06ANBEKDI0UADLJgNoGyXBAAA.d9gAH_gAAAAAAAAAAAA";
let cmpApi = new CmpApi(CMP_ID, CMP_VERSION, IS_SERVICE_SPECIFIC);
cmpApi.update(testTCString, false);
cmpApi.update(testTCString, false);
cmpApi.update(testTCString, false);
```
Here the console output is:
```
tcloaded
useractioncomplete
useractioncomplete
```
I think that it should only be one `tcloaded` since between those calls there was not `cmpuishown`.

**Example 2 - Firing multiple cmpApi update with `uiVisible=true`:**
```
window.__tcfapi('addEventListener', 2, (tcData) => console.log(tcData.eventStatus));
let testTCString = "COeTFulOk0pYVBiAKDENAXCsABCAACmAACZYA3oOAIQAQCICAwIsguI06ANBEKDI0UADLJgNoGyXBAAA.d9gAH_gAAAAAAAAAAAA";
let cmpApi = new CmpApi(CMP_ID, CMP_VERSION, IS_SERVICE_SPECIFIC);
cmpApi.update(testTCString, true);
cmpApi.update(testTCString, true);
cmpApi.update(testTCString, true);
```
Here the console output is:
```
cmpuishown
cmpuishown
cmpuishown
```
I think that it should only be one `cmpuishown` event triggered.

**Comment by chrispaterson** [comment]
thanks @nejcsever.  I can see the subsequent `false`'s should be `tcloaded` each time but the subsequent `true`'s I'm not sure what you could put there instead of `cmpuishown`.  Because if you're saying the UI is visible, then you're saying the CMP UI is shown and that's really an error on the CMP, do you agree?

**Comment by nejcsever** [comment]
I agree.

**Comment by chrispaterson** [comment]
I'll work to fix the `false` case

**Comment by chrispaterson** [comment]
This is fixed now
