### ISSUE TITLE
Stub not published to cdn?

### ISSUE THREAD

**Issue by sebzap** [InteractiveAdvertisingBureau/iabtcf-es#138]
A publisher that is using our tool is loading the stub module from cdn: `https://cdn.opencmp.net/tcf-v2/cmp-stub-latest.js`
Which throws errors when sending postMessages to call the __tcfapi.

The cdn script does not call `__tcfapi` correctly when receiving post messages:

![image](https://user-images.githubusercontent.com/12527892/78003128-7d8d5a80-7338-11ea-99fc-58c0cc72108c.png)

However, this error is not on the master branch: https://github.com/InteractiveAdvertisingBureau/iabtcf-es/blob/3130f29569904adfc4505ee3f3630fdcc48a1a39/modules/stub/src/stub.js#L133-L156

**Comment by chrispaterson** [comment]
Sounds like if the latest master branch doesn't have the error, then whoever runs opencmp.net should update their version?  I'm not sure how I can help here...

**Comment by sebzap** [comment]
sry, i mistakenly assumed this was some official distribution. never mind then.
