### ISSUE TITLE
Unable to set and unset individual purposes, specialFeatures, or vendors

### ISSUE THREAD

**Issue by tboneearls** [InteractiveAdvertisingBureau/iabtcf-es#140]
**Version**
1.0.0-beta.29

**Module (core, cmpapi, cli, stub, or testing)**
Core
**Describe with reproduction steps – What is the expected behavior?**

Here's a simplified version of our implementation to reproduce the error:
```
var tcf2core = require('@iabtcf/core');
var tcModel = new tcf2core.TCModel(new tcf2core.GVL());
// wait for tcModel readyPromise...

// when we try to save based on opted in purposes

var optedInPurposeIds = [1,2,3]; // purposes the user has selected
tcModel.purposeConsents.set(optedInPurposeIds);
tcf2core.TCString.encode(tcModel); // throws error

// at this point we'd want to set a consent cookie after encoding, but cannot
```

The error I'm seeing is a circular dependency issue. As far as I can tell, the issue is that we're passing an array of ids, but according to the example given [here](https://github.com/InteractiveAdvertisingBureau/iabtcf-es/tree/master/modules/core#tcmodel), this is the pattern we're supposed to follow to implement setting purposes, specialFeatures, and vendors on an individual basis.

Here's a copy of the error.

```
Uncaught (in promise) TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'vendors' -> object with constructor 'Array'
    |     index 0 -> object with constructor 'Object'
    |     property 'purposes' -> object with constructor 'Array'
    --- index 0 closes the circle
    at JSON.stringify (<anonymous>)
```

Since there is no documented way to work with this, I'm unsure there's an officially supported method to support this use case, which is required in order to be fully compliant with TCF 2.0. 

Resolution would be either updating the documentation with the correct methodology, or adding the functions we need. It would be nice to have a public set of methods like `setPurposes(arrayOfPurposeIds)` etc. that would take an array of ids and set or unset them in the TCModel.

This is related to PR #74 but I'm opening this separate issue because this isn't simply a lack of documentation.

**Comment by chrispaterson** [comment]
Hi @tboneearls,  To me, your code seems to be the intended use.  I know documentation is lacking and I apologize for that – I've been trying to write this library, respond to bug reports and launch our own company's CMP and I'm afraid the documentation has fallen to the wayside.  Here I have created a test case derived from your example and it passes:

https://github.com/InteractiveAdvertisingBureau/iabtcf-es/blob/140/modules/core/test/ReportedIssues.test.ts#L155

**Comment by tboneearls** [comment]
Thanks for your quick response. Much appreciated. Since your test case is passing, perhaps the error I'm seeing is coming from my implementation then. It's good to know that I was following the correct pattern though.

**Comment by chrispaterson** [comment]
Ok, I'm going to close the issue then and work on the documentation through issue #74
