### ISSUE TITLE
CmpApi incorrectly invalidates TC strings with no publisherTC segment

### ISSUE THREAD

**Issue by nealrosen04** [InteractiveAdvertisingBureau/iabtcf-es#141]
**Version**
1.0.0-beta.29

**Module (core, cmpapi, cli, stub, or testing)**
cmpapi

**Describe with reproduction steps – What is the expected behavior?**
Pass a valid tc string to the CMP API that does not contain a publisherTC segment.  The string should be considered valid.  The CMP API is instead throwing an exception from CmpApi:throwMaybe().

According to the TCF spec..
"The Core String is always required and comes first and includes all the details required for communicating basic vendor transparency and consent. The remaining optional and arbitrarily ordered segments represent support for out-of-band (OOB) signaling and publisher purposes transparency and consent (publisher TC). A TC String with all four segments is possible in certain conditions."

**Comment by chrispaterson** [comment]
in 1.0.0-beta.32
