### ISSUE TITLE
Base64Url.ts uses Buffer without import

### ISSUE THREAD

**Issue by kubi** [InteractiveAdvertisingBureau/iabtcf-es#143]
**Version**
1.0.0-beta.30

**Module (core, cmpapi, cli, stub, or testing)**
core

**Describe with reproduction steps – What is the expected behavior?**
Should be able to encode TCModel in a browser.

Browsers do not support Buffer objects

**Comment by chrispaterson** [comment]
This duplicates #145 I just pushed a patch in 1.0.0-beta.31
