### ISSUE TITLE
GVLError XMLHttpRequest.response is undefined on NodeJs

### ISSUE THREAD

**Issue by sandeepmuchrla** [InteractiveAdvertisingBureau/iabtcf-es#144]
GVLError XMLHttpRequest.response is undefined on NodeJs 
also we get content in  XMLHttpRequest.responseText

Refer the following code
//GVL base url is set

const tcModel = new TCModel(new GVL());

 tcModel.gvl.readyPromise.then(() => {

  // Set values on tcModel...

  const encodedString = 'TCString.encode(tcModel);

});

**Comment by chrispaterson** [comment]
Hi, for now you'll have to use an XHR polyfill in NodeJS like https://github.com/pwnall/node-xhr2

**Comment by spencerwyckoff** [comment]
@chrispaterson Wanted to make sure that updating the HTTP Request approach for fetching the GVL doesn't take us out of compliance with the policies in anyway.  We aren't changing anything with the string encoding or any of that... just the mechanism for getting Vendor List data from server.

**Comment by chrispaterson** [comment]
@spencerwyckoff fetching via HTTP request does not take us out of compliance with policies to my knowledge.  I'm not following how it would?

**Comment by spencerwyckoff** [comment]
cool - just trying to get your thoughts and a confirmation - the way we're interacting with this .js file requires us to change the source code, but only to update how the HTTP request is made.
