### ISSUE TITLE
Buffer method is not defined in chrome

### ISSUE THREAD

**Issue by mghouse036** [InteractiveAdvertisingBureau/iabtcf-es#145]
**Version**
1.0.0-beta.30
**Module (core, cmpapi, cli, stub, or testing)**
core
**Describe with reproduction steps – What is the expected behavior?**
Buffer is node specific method which is not supported on browsers.
https://github.com/InteractiveAdvertisingBureau/iabtcf-es/blob/7d42a45397a63d891f3a35b15b43f440d28add5e/modules/core/src/encoder/Base64Url.ts

**Comment by chrispaterson** [comment]
What I can't understand is that it works...  How is that possible?

**Comment by mghouse036** [comment]
@chrispaterson, Is it feasible to publish this in early next week ?

**Comment by chrispaterson** [comment]
It’s already published :-)

**Comment by laurent-chriqui** [comment]
Are you sure this is correct ?

https://github.com/InteractiveAdvertisingBureau/iabtcf-es/commit/082e3dfb5da6f240476bf6ea2f9062444c6d7230#r38489103
