### ISSUE TITLE
getTCData returns empty objects for purposes

### ISSUE THREAD

**Issue by scottishstoater** [InteractiveAdvertisingBureau/iabtcf-es#149]
Apologies in advance if this is a knowledge gap from me, I'm relatively new to the iAB world. 

I'm trying to use `getTCData` to extract purpose consent data from the `TC Model` using the function below [as per the documentation](https://documentation.sourcepoint.com/web-implementation/sourcepoint-gdpr-and-tcf-v2-support-beta/the-__tcfapi-gettcdata-api-overview).

```js
__tcfapi('getTCData', 2, (tcData, success) => {
    if(success) {
        console.log(tcData);                
    }
});
```

The function returns:

```json
{
  "tcfPolicyVersion": 2,
  "cmpId": 259,
  "gdprApplies": true,
  "eventStatus": "cmpuishown",
  "cmpStatus": "loaded",
  "isServiceSpecific": true,
  "useNonStandardStacks": false,
  "publisherCC": "GB",
  "purposeOneTreatment": false,
  "publisher": {
    "consents": {},
    "legitimateInterests": {},
    "customPurpose": {
      "consents": {},
      "legitimateInterests": {}
    },
    "restrictions": {}
  },
  "tcString": "COxlfpbOxlfpbEDAJBAAAgCuAP_AAP_AAAwIF3EXySoGY2tho2YVFzBEIYwfJxyigMgShgQIsS0NQIeFLBoGPiAAHBGYJAQAGBAkkACBAQIsHGBMCQABgAgRiRCMQEGMDzNIBIBAggkbY0FACCVmnkHS3ZCY70-6u__QLuIvklQMxtbDRswqLmCIQxg-TjlFAZAlDAgRYloagQ8KWDQMfEAAOCMwSAgAMCBJIAECAgRYOMCYEgADABAjEiEYgIMYHmaQCQCBBBI2xoKAEErNPIOluyEx3p91d_-gAA",
  "listenerId": null,
  "purpose": {
    "consents": {},
    "legitimateInterests": {}
  },
  "vendor": {
    "consents": {},
    "legitimateInterests": {}
  },
  "specialFeatureOptins": {}
}
```

My understanding of the documentation [here](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20CMP%20API%20v2.md#tcdata) is that `purpose.consents` should contain 10 keys with `bool` values, which is what I'm trying to access. 

When I decode the `tcString` in the returned object at [iabtcf.com/#/decode](https://iabtcf.com/#/decode) it shows that "Purpose Consents" does hold this information. 

Is there any reason why the function would be returning empty objects for these keys? 

Thanks,
Chris

**Comment by chrispaterson** [comment]
I'm not sure; when I put that TC String through the cmpapi script it gives me exactly what the iabtcf.com site does...

**Comment by scottishstoater** [comment]
@chrispaterson Thank you for your quick reply. The issue was with my CMP provider. It was a teething issue with their v2 implementation. 

Sorted now! :)
