### ISSUE TITLE
Publisher Custom Purposes (consent and legitimate interest) should be variable length encodings

### ISSUE THREAD

**Issue by chrispaterson** [InteractiveAdvertisingBureau/iabtcf-es#150]
**Version**
since 1.0.0-beta.4

**Module (core, cmpapi, cli, stub, or testing)**
core

**Describe with reproduction steps – What is the expected behavior?**
mentioned https://github.com/InteractiveAdvertisingBureau/iabtcf-es/issues/125#issuecomment-612114223 

Custom purposes for publishers should not have a bit length property and instead should be a variable length encoding.

**Comment by lchriqui** [comment]
👍

**Comment by laurent-chriqui** [comment]
👍
