### ISSUE TITLE
Consents for non-tcf vendors

### ISSUE THREAD

**Issue by yogeshmuli** [InteractiveAdvertisingBureau/iabtcf-es#151]
As shown in IAB's sample implementation for tcfv2. the publisher can have vendors that are not part of tcf. In such case can we or should we take consent for those vendors in a way that we are taking for custom purposes or Publisher need to handle it separately.

**Comment by chrispaterson** [comment]
I'm not sure how this would work exactly.  This may be something that needs to be discussed in the TCF Working groups.  I know that non-IAB vendors are not permitted to use the IAB purposes and are not covered under 'the framework'.
