### ISSUE TITLE
Legal basis purpose restriction is reflected on vendors without flexible purposes too

### ISSUE THREAD

**Issue by matita** [InteractiveAdvertisingBureau/iabtcf-es#162]
**Version**

`1.0.1-3`

**Module (core, cmpapi, cli, stub, or testing)**

`core`

**Describe with reproduction steps – What is the expected behavior?**

As far as I understand legal basis purposes restrictions should only affect vendors that specified the restricted purpose as flexible (see [spec](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20Consent%20string%20and%20vendor%20list%20formats%20v2.md#what-are-publisher-restrictions)), while even vendors that have no flexible purpose appear as restricted in the consent string.

Code to reproduce the issue:

```js
const gvl = new GVL(36);
gvl.readyPromise.then(() => {
  // Vendor 4 does not have any flexible purpose at GVL version 36
  const vendorId = 4;
  // Vendor 4 specifies purpose 2 as consent purpose
  const purposeId = 2;
  const tcModel = new TCModel(gvl);
  const purposeRestriction = new PurposeRestriction(purposeId, RestrictionType.REQUIRE_LI);
  tcModel.publisherRestrictions.add(vendorId, purposeRestriction);

  if (tcModel.publisherRestrictions.vendorHasRestriction(vendorId, purposeRestriction)) {
    throw new Error(`Vendor ${vendorId} has legal basis restriction over purpose ${purposeId} even though that purpose is not flexible`);
  }
});
```

The problem seems to be in this `if...else if` which has no `else` clause. https://github.com/InteractiveAdvertisingBureau/iabtcf-es/blob/2443ca1dc7f9c85342b28fea8b8da5d50a4a32eb/modules/core/src/model/PurposeRestrictionVector.ts#L46-L75

Thus this function returns `true` like it didn't have any GVL set, as suggested by the comment (while it should return `false`). https://github.com/InteractiveAdvertisingBureau/iabtcf-es/blob/2443ca1dc7f9c85342b28fea8b8da5d50a4a32eb/modules/core/src/model/PurposeRestrictionVector.ts#L86-L87

Or am I misinterpreting the spec?

**Comment by chrispaterson** [comment]
thanks @matita

**Comment by chrispaterson** [comment]
I put in a fix.  The code requires you to set the GVL on the purposeRestrictionVector to remove restrictions that don't make sense.  I now make the TCString encoder do that before encode.  But before the string is encoded if the GVL isn't set, the class doesn't have a way of knowing what is flexible or not.
