### ISSUE TITLE
Storage And Access LI TC string encoding is not correct

### ISSUE THREAD

**Issue by tomsivan** [InteractiveAdvertisingBureau/iabtcf-es#167]
**Version**

**Module (core, cmpapi, cli, stub, or testing)**

**Describe with reproduction steps – What is the expected behavior?**

**Comment by chrispaterson** [comment]
With no information in this ticket, I can not verify.

**Comment by tomsivan** [comment]
Hi Chris,

I tried using the encoder tool in order to get the TC string that
represents storage and access LI.

When doing that I noticed that the string does not change if the storage
and access LI purpose is selected or not.

**Comment by chrispaterson** [comment]
@tomsivan that is actually by design.  A Vendor is not allowed to have Purpose 1 (storage and access) set to 1 for Legitimate Interest.

**Comment by tomsivan** [comment]
Oh wow...
Did not see that ;)
