### ISSUE TITLE
Separate module with typings only

### ISSUE THREAD

**Issue by muuki88** [InteractiveAdvertisingBureau/iabtcf-es#172]
Hi,

Thanks for this amazing project :heart: We are a publisher and use it to test and integrate the new TCF 2 consent platform.

As a publisher we don't implement our own CMP, but we integrate with a cmp provider and use the `_tcfapi` to check purpose and vendor consents for 3rd party modules we have integrated (e.g. google analytics). 

It would be very helpful if the typings for the `__tcfapi` interface would be available as a separate module that we could use. At the moment we are writing the typings ourselves and the ones in this project are a bit scattered over the `core` and `cmpapi` module.

thanks a lot for your work,
Muki

**Comment by chrispaterson** [comment]
It looks like DefinitelyTyped only wants modules for non-typescript projects.  Since this project is all written in TypeScript you should have access to the types by including the modules in your dependencies.  I don't think it needs its own type-only module.  That being said let me make the `@iabtcf/cmpapi` types more accessible for a publisher.

**Comment by muuki88** [comment]
Thanks for taking the time to work on this 👍😊

**Comment by derdeka** [comment]
@chrispaterson why not just move all Interfaces from @iabtcf/core to a separate @iabtcf/spec package? This would also help to decouple @iabtcf/cmpapi from @iabtcf/core

**Comment by chrispaterson** [comment]
@muuki88 I've cleaned up the exported interfaces quite a bit in the @iabtcf/cmpapi package.  I just released this in pre-minor version 1.1.0-0.  This should help calling scripts, let me know if it works for you

**Comment by muuki88** [comment]
Awesome. Hopefully I can try it out on Monday 😊👍

**Comment by muuki88** [comment]
Thanks for your work @chrispaterson . What I was looking for is something you mocked in the tests: https://github.com/InteractiveAdvertisingBureau/iabtcf-es/blob/e8e73b488f18183ac65a885e11e55558d6886ad3/modules/cmpapi/test/Root.test.ts#L8-L15

A `CmpApiWindow` interface that contains the standard API that I can call from my site as a publisher :smile:
