### ISSUE TITLE
Base64Url - Extra padding on strings that are already of length LCM

### ISSUE THREAD

**Issue by pgoforth** [InteractiveAdvertisingBureau/iabtcf-es#178]
While attempting to implement the TCF framework into the [Osano](https://www.osano.com) consent manager, I came across an issue while attempting to validate TCStrings that were already of a bit length that was a factor of 24 (the LCM of 6 and 8 being used in the `encode` method).

Currently, if you try to encode a string that is already of length === `LCM`, an unnecessary string of zeros of LCM length will be added to your bit string.
https://github.com/InteractiveAdvertisingBureau/iabtcf-es/blob/488660c97bb2e72c37f1854a47b8d7938927a1ae/modules/core/src/encoder/Base64Url.ts#L52

I have made a PR to resolve the issue:
https://github.com/InteractiveAdvertisingBureau/iabtcf-es/pull/177

**Comment by chrispaterson** [comment]
In pre-release version 1.1.0-0
