### ISSUE TITLE
Wrap built-in command responses

### ISSUE THREAD

**Issue by chrispaterson** [InteractiveAdvertisingBureau/iabtcf-es#180]
**Describe the feature you'd like**

Currently, `customCommands` will redefine built-in commands if defined.  To enable CMPs to "enhance" responses with other information it would be more ideal if instead the custom command gets called after the built-in response as a sort of middleware.

**example**
```javascript
const cmpApi = new CmpApi(CMP_ID, CMP_VERSION, true, {

  "getTCData": (tcData, next) => {

    tcData.myCustomProperty = 'banana';
    next(tcData);

  }

});
```

Or promise style:

**example**
```javascript
const cmpApi = new CmpApi(CMP_ID, CMP_VERSION, true, {

  "getTCData": (tcData) => {

    return new Promise((resolve, reject) => {

      tcData.myCustomProperty = 'banana';
      resolve(tcData);

    });

  }

});
```

**Comment by chrispaterson** [comment]
This will enable #176

**Comment by chrispaterson** [comment]
In pre-release 1.1.0-0

**Comment by jawadst** [comment]
@chrispaterson Thanks for your work on this! We'd like to start using this feature. Is the pre-release safe to use in production?
