### ISSUE TITLE
Unclear how to Unit Test Vendor Consents being set in TCModel

### ISSUE THREAD

**Issue by tboneearls** [InteractiveAdvertisingBureau/iabtcf-es#181]
**Version**
1.0.2-3 and greater
**Module (core, cmpapi, cli, stub, or testing)**
core
**Describe with reproduction steps – What is the expected behavior?**

My team is unable to upgrade our IAB dependencies due to newly failing unit tests. We are asserting that we can set a vendorConsent into the tcModel, encode the TCString and set as a browser cookie, decode the cookie (which is an encoded TCString), and then be able to retrieve the vendorConsent that was initially set. 

it seems like my issue is related to #171 which now checks the TCString prior to encoding and strips out any vendors with no purposes declared. It's undocumented how to unit test against this API change, and what the best practice is. This being the case, I'm not sure if I've discovered a bug, or if I'm using the API incorrectly.

However, even when doing something like this (trying to decouple from our app-specific code as much as possible):

```
import { GVL, TCModel, TCString } from '@iabtcf/core';

it("should set a vendorConsent in the TCString cookie", function() {
     var tcModel = new TCModel(new GVL());
     
     // the GVL vendor with id 9 has all 10 purposes associated with it
     tcModel.vendorConsents.set(9);

     var cookieKey = "euconsent-v2";

     // console logging cookieVal shows the vendor consent is already removed from the TCString
     var cookieVal = TCString.encode(tcModel);

     // set the tcModel into the document.cookie
     document.cookie = cookieKey + "=" + cookieVal + ";";

     // get the encoded consent cookie
     var encodedConsentCookie = document.cookie
           .split('; ')
           .find(row => row.startsWith('euconsent-v2'))
           .split("=")[1]

     var decodedConsentData = TCString.decode(encodedConsentCookie);

     // this assertion fails
     expect(decodedConsentData.vendorConsents.length).toEqual([9]);
}
```

The assertion above fails, even though in the GVL there are 10 purposes associated with this vendor of id 9. If this vendor had no associated purposes, I would expect this test case to fail, but that is not the case. Am I missing something in my test case, or did I discover a bug? 

Either way, improved documentation around this would be greatly appreciated.

**Comment by chrispaterson** [comment]
your `decodedConsentData.vendorConsents` is a [`Vector`](https://github.com/InteractiveAdvertisingBureau/iabtcf-es/blob/master/modules/core/src/model/Vector.ts) so it does not have a `length` property – It's not an `Array`.  So this assertion:
```javascript
expect(decodedConsentData.vendorConsents.length).toEqual([9]);
```

Should either be
 
```javascript
expect(decodedConsentData.vendorConsents.has(9)).toEqual(true);
```

or if you're checking that only vendor 9 is set:

```javascript
for(var i = 1; i <= decodedConsentData.vendorConsents.maxId; i++) {

  expect(decodedConsentData.vendorConsents.has(9)).toEqual((i === 9));

}
```

If you'd like more ideas for testing, I have written a bunch of tests for [`Vector` here](https://github.com/InteractiveAdvertisingBureau/iabtcf-es/blob/master/modules/core/test/model/Vector.test.ts) 

[The TCString tests are very similar to your test too.](https://github.com/InteractiveAdvertisingBureau/iabtcf-es/blob/master/modules/core/test/TCString.test.ts)

Also, I've written a bunch of testing utilities (with almost no documentation) as a module named `@iabtcf/testing`.  [You can find that here](https://github.com/InteractiveAdvertisingBureau/iabtcf-es/tree/master/modules/testing).

**Comment by tboneearls** [comment]
Ah woops. It appears I made a typo in that line you mentioned. The test that I have is more like this:

`expect(decodedConsentData.vendorConsents).toEqual([9])`

Thanks for pointing out that testing module. I will take a look at that.

**Comment by tboneearls** [comment]
@chrispaterson this still isn't working for me. After adjusting my test as follows, it still fails:

```
import { GVL, TCModel, TCString } from '@iabtcf/core';

it("should set a vendorConsent in the TCString cookie", function() {
     var tcModel = new TCModel(new GVL());
     
     // the GVL vendor with id 9 has all 10 purposes associated with it
     tcModel.vendorConsents.set(9);

     var cookieKey = "euconsent-v2";

     // console logging cookieVal shows the vendor consent is already removed from the TCString
     var cookieVal = TCString.encode(tcModel);

     // set the tcModel into the document.cookie
     document.cookie = cookieKey + "=" + cookieVal + ";";

     // get the encoded consent cookie
     var encodedConsentCookie = document.cookie
           .split('; ')
           .find(row => row.startsWith('euconsent-v2'))
           .split("=")[1]

     var decodedConsentData = TCString.decode(encodedConsentCookie);

     // this assertion fails
     expect(decodedConsentData.vendorConsents.has(9)).toEqual(true);
}
```

Also, when I console.log the encoded `cookieVal` and pass it into the iab's [decoding tool](https://iabtcf.com/#/decode), I don't see that the vendor consent is set there, despite there being purposes associated with this vendor id in the GVL. Please assist. This seems to be a bug because the encoding should only remove vendors with no purposes set.

**Comment by chrispaterson** [comment]
@tboneearls I ran your tests and got them to pass by:

1. Take out the cookie setting of the equation.
  - it's not really necessary to test whether you can set and read a cookie because that's base browser functionality.  Doing this makes the testing less discrete and forces the test to depend on the environment more.
2. Wait for the GVL `readyPromise`
  - Assuming you're GVL is set up correctly and valid (ie.`GVL.baseUrl` is set beforehand), the action of fetching the `vendor-list.json` is asynchronous and the `TCModel` can not be encoded without the `vendor-list.json`.
3. Set a `cmpId` in the `TCModel`
  - If the `cmpId` is the default `0` the encoder will throw an error and will not encode the string.
4. change `expect(...).toEqual(...)` to `expect(...).to.be.true`
  - Your assert library may be ok with this, but mine didn't work.

My working version of your assertion looks like this:
```javascript
import { GVL, TCModel, TCString } from '@iabtcf/core';
import { makeRandomInt, GVLFactory } from '@iabtcf/testing';

it('should set a vendorConsent in the TCString cookie', function(done) {
  
  var gvl = GVLFactory.getLatest();
  var tcModel = new TCModel(gvl);

  // leaving as 0 throws an error on encode
  tcModel.cmpId = makeRandomInt(1, 100);

  // the GVL vendor with id 9 has all 10 purposes associated with it
  tcModel.vendorConsents.set(9);

  // wait for gvl to be "ready"
  gvl.readyPromise.then(function() {                                                                                                                                                                                                                                
  
        // console logging cookieVal shows the vendor consent is already removed from the TCString
        var encoded = TCString.encode(tcModel);

        var decodedConsentData = TCString.decode(encoded);
    
        // this assertion fails
        expect(decodedConsentData.vendorConsents.has(9)).to.be.true;

        done();
  
      });
  
    });
```

Let me know what the result of this is

**Comment by tboneearls** [comment]
I'm not sure that removing the browser component of our testing makes sense for our use case. We're not trying to validate the iabtcf internals are working, but rather that it works in conjunction with our implementation in the browser that we're supplying to our clients who need to be tcf compliant.

My unit testing library is jasmine. It appears that this is now working for me when I use the testing library. However, the `@iabtcf/testing` module requires a `chai` installation, or else it throws an error when using any of the utility functions. 

I'm not sure this can be easily fixed if there's a dependency on it, but it might be worth listing this peer dependency on the README.
