### ISSUE TITLE
Support for new languages rs-cyrillic and rs-latin

### ISSUE THREAD

**Issue by mmuras** [InteractiveAdvertisingBureau/iabtcf-es#183]
**Version**
Any

**Module (core, cmpapi, cli, stub, or testing)**
Core

**Describe with reproduction steps – What is the expected behavior?**
setting "rs-cyrillic" or "rs-latin" as parameter for gvl.changeLanguage() method throws Error

Please add this languages:
https://vendorlist.consensu.org/v2/purposes-rs-cyrillic.json
https://vendorlist.consensu.org/v2/purposes-rs-latin.json

to the list of known ones.

**Comment by mmuras** [comment]
Also according to spec: https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20Consent%20string%20and%20vendor%20list%20formats%20v2.md#the-core-string ConsentLanguage stored inside consent string should be written according to SO_639-1 https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes  so it should be "sr" probably

**Comment by chrispaterson** [comment]
According to the [policies](https://iabeurope.eu/iab-europe-transparency-consent-framework-policies/). Only officially supported translations are supported.  You'll have to request this of IAB Europe.

**Comment by mmuras** [comment]
But this translations are official: https://register.consensu.org/Translation
