### ISSUE TITLE
GVL.consentLanguages returns empty object

### ISSUE THREAD

**Issue by rdalmas** [InteractiveAdvertisingBureau/iabtcf-es#190]
**Version** 1.0.2-3

**Module (core, cmpapi, cli, stub, or testing)** core

**Describe with reproduction steps – What is the expected behavior?**

There is a method on the CMP to check wether the language is supported by IAB before it triggers the actual change, as a safe check. Within this check, it's used the 'GVL.consentLanguages' as below:

```
if (GVL.consentLanguages).has(givenLanguage) {
... do the language change
}
... change to fallback language (en)
```

I was implementing some tests and notice they were failing. So I decided to debug it and came across the fact that consentLanguages was an empty object, explaining the reason why the language was always set to EN in my unit tests.

It might be that I should't use that property to check the supported languages by IAB, if that's the case, please close the issue and give me a valid alternative, if any. :)

Thanks in advance!

**Comment by chrispaterson** [comment]
This [`ConsentLanguages`](https://github.com/InteractiveAdvertisingBureau/iabtcf-es/blob/master/modules/core/src/model/ConsentLanguages.ts) class is the object that gets assigned to the `GVL.consentLanguages` 

[The GVL will check internally as you set the language if it is supported and will throw an error if it doesn't.](https://github.com/InteractiveAdvertisingBureau/iabtcf-es/blob/master/modules/core/src/GVL.ts#L424)

**Comment by chrispaterson** [comment]
@rdalmas were you able to get this resolved?
