### ISSUE TITLE
vendorConsents empty when decoding TCF 1.1 consentString that uses vendorRangeList

### ISSUE THREAD

**Issue by CaptSnooze** [InteractiveAdvertisingBureau/iabtcf-es#191]
**Version**
1.1.0-0

**Module (core, cmpapi, cli, stub, or testing)**
core

**Describe with reproduction steps – What is the expected behavior?**

- Decode a **ConsentString from TCF 1.1 that uses vendorRangeList** for vendors, allowing all vendors in a given range
- Example String: BO2e4qiO2e4qiB9ABADEDS-AAAAxKABgACBiQA created via [TCF v1.1 Consent String SDK - javascript](https://github.com/InteractiveAdvertisingBureau/Consent-String-SDK-JS/), allowing all listed vendors on list version 210 from ID min:1 to max:786 = 503.
- Decode above 1.1 ConsentString **using this Lib**
- check list of allowed vendors: TCString.decode('BO2e4qiO2e4qiB9ABADEDS-AAAAxKABgACBiQA').vendorConsents.size
- Expected Result: all 503 vendors
- Actual Result: 0 vendors, vendorConsents empty.

Is this Lib supposed to correctly decode TCF 1.1 ConsentStrings (or only 2.0 TCStrings)?
Apologies if this is the wrong forum for this question.

**Comment by chrispaterson** [comment]
I wrote the code in a way to support multiple versions, however I wasn't sure there was much demand for it so I never tested it.

**Comment by chrispaterson** [comment]
But the issue does make sense because a "vendor vector" in the string has slightly different fields in v1 vs v2 which are unaccounted for in the decoder.
