### ISSUE TITLE
Documentation Slightly out of Date

### ISSUE THREAD

**Issue by potench** [InteractiveAdvertisingBureau/iabtcf-es#197]
**Version**
1.1.0-1

**Module (core, cmpapi, cli, stub, or testing)**
`core` and core documentation https://iabtcf.com/api/core/classes/tcmodel.html#setallpurposelegitimateinterest 

**Describe with reproduction steps – What is the expected behavior?**
Documentation for the `tcModel` hasn't been updated to match the current tcModel API. Took some effort to figure out why individual calls were failing.

Actual APIs:
  * [setAllSpecialFeatureOptins()](https://github.com/InteractiveAdvertisingBureau/iabtcf-es/blob/master/modules/core/src/TCModel.ts#L620)
  * [setAllVendorLegitimateInterests()](https://github.com/InteractiveAdvertisingBureau/iabtcf-es/blob/master/modules/core/src/TCModel.ts#L554)
  * [setAllPurposeLegitimateInterests()](https://github.com/InteractiveAdvertisingBureau/iabtcf-es/blob/master/modules/core/src/TCModel.ts#L598)

Documented APIs
  * [setAllSpecialFeatureOptIns](https://iabtcf.com/api/core/classes/tcmodel.html#setallspecialfeatureoptins) (uppercase "I" is incorrect)
  * [setAllPurposeLegitimateInterest](https://iabtcf.com/api/core/classes/tcmodel.html#setallpurposelegitimateinterest) (singular is incorrect)
  * [setAllVendorLegitimateInterest](https://iabtcf.com/api/core/classes/tcmodel.html#setallvendorlegitimateinterest) (singular is incorrect)

**Comment by chrispaterson** [comment]
Fully aware of this... I generated those a long time ago.  I'm planning on going through and handwriting documentation.

**Comment by chrispaterson** [comment]
I'm going to close this because I'm trying to work on documentation on the https:www.iabtcf.com site https://github.com/InteractiveAdvertisingBureau/iabtcf
