### ISSUE TITLE
PurposeRestrictionVector

### ISSUE THREAD

**Issue by woggle23** [InteractiveAdvertisingBureau/iabtcf-es#201]
**Version**
1.1.0-1

**Module (core, cmpapi, cli, stub, or testing)**
core

**Describe with reproduction steps – What is the expected behavior?**
`publisherRestrictions` don't seem to be set correctly.

Consider some vendor with the following:
```
"1":{
         "id":1,
         "name":"Vendor 1",
         "purposes":[
            1,
            2     
         ],
         "legIntPurposes":[
            3
         ],
         "flexiblePurposes":[
            3
         ],
         "specialPurposes":[],
         "features":[],
         "specialFeatures":[],
         "policyUrl":"https://vendor1.com/privacy"
      }
```

The above has a declared purpose 3 as a `flexiblePurpose`, with `legInt` as its default. If I add a publisher restriction for `purpose 3` with a restriction of `RestrictionType.REQUIRE_CONSENT`, `publisherRestrictions.getVendors()` should return `[1]`; it doesn't at the minute.

It looks like the problem is [here](https://github.com/InteractiveAdvertisingBureau/iabtcf-es/blob/fd137351359c346ce2eb45ecc4408909bebf8c41/modules/core/src/model/PurposeRestrictionVector.ts#L68); you need to add `break;` after the above line.

**Comment by chrispaterson** [comment]
yikes!  Thanks for reporting this
