### ISSUE TITLE
__tcfapi('getTCData') callback is not sync

### ISSUE THREAD

**Issue by matita** [InteractiveAdvertisingBureau/iabtcf-es#202]
**Version**
1.1.0-1

**Module (core, cmpapi, cli, stub, or testing)**
cmpapi

**Describe with reproduction steps – What is the expected behavior?**
A code is worth a thousand words:

```js
var a;
__tcfapi('getTCData', 2, res => { a = res; });
console.log(a); // outputs `undefined`, used to output `res` value in v1.0.1-3
setTimeout(() => console.log(a)); // correctly outputs `res` value
```

It seems like the callback is not invoked synchronously anymore.

**Comment by invi2000** [comment]
@chrispaterson 
Any ETA on releasing 1.1.0 or at least this fix as a hotfix? We (as Rakuten Advertising) have problems getting proper consent and validating new clients because we rely on the API to return results immediately. 
Thanks!
