### ISSUE TITLE
Not possible to set vendorConsent for vendor which declared felxiblePurposes but no purposes

### ISSUE THREAD

**Issue by jelenatomcic** [InteractiveAdvertisingBureau/iabtcf-es#204]
**Version**
1.1.0-2
**Module (core, cmpapi, cli, stub, or testing)**
@iabtcf/core
**Describe with reproduction steps – What is the expected behavior?**
As stated in the title, setting vendorConsent in TCModel for a vendor which declared flexiblePurposes (and no consent purposes) does not result in positive vendorConsent signal in TCString. Vendors from the current GVL with such setting (as example):
- A Million Ads Ltd
- Blue Billywig BV
- Cavai AS & UK
- Effinity
- INFOnline GmbH
- Kiosked Ltd

Expected behaviour is that vendorConsent positive signal appears in TCString for vendors with flexiblePurposes.

**Comment by chrispaterson** [comment]
I just tried replicating your issue, but I can't seem to do so.  [Can you look at the unit test I created](https://github.com/InteractiveAdvertisingBureau/iabtcf-es/commit/d2d6857af600cc6b3a72eb360358eba19f176628) and see what I'm doing wrong?

**Comment by opencmp** [comment]
@chrispaterson Same here, if the vendor has no purposes defined, **the API always returns false** on the vendor consent.
I prepared screenshots for two examples:
![image](https://user-images.githubusercontent.com/64460045/89972024-5f911880-dc8f-11ea-883d-d47742a29304.png)
![image](https://user-images.githubusercontent.com/64460045/89972058-720b5200-dc8f-11ea-82a5-ecdcf92dc4ae.png)

I can set them in the TCModel, but the API will always return false for them. You can see that also in the CMP Validator, where there are red lines for missing vendor consents even if you allowed everything in the CMP. The consent also gets lost in the UI after parsing the TCString.

We would appreciate if this can be commented or solved quickly as our publishers are going live today. Thank you!

**Comment by chrispaterson** [comment]
@opencmp I think 646 would be accurate, there's no way they can ever get consent.  They have no purposes.  I would even venture to say why are they even on the GVL?  features are not accounted for in signaling at all.

784 also should never get a consent signal because they have only legitimate interest signals.  Someone has pointed out that flexible purposes (if overrides) should be setting their consent values when overriden and it currently isn't, which is what I will fix.

**Comment by opencmp** [comment]
Thank you very much, that clarifies a lot @chrispaterson

**Comment by opencmp** [comment]
@chrispaterson This problem still exists in version @iabtcf/core@1.1.4. Vendors with no Purpose but Flexible Purposes lose their signal:
![grafik](https://user-images.githubusercontent.com/64460045/96223120-0069c000-0fc0-11eb-87de-3837154bd490.png)
Is there any deadline for the fix?
