### ISSUE TITLE
GVL.changeLanguage failing in Internet Explorer

### ISSUE THREAD

**Issue by jonas-veselka** [InteractiveAdvertisingBureau/iabtcf-es#206]
**Version**
1.0.1

**Module (core, cmpapi, cli, stub, or testing)**
Core

**Describe with reproduction steps – What is the expected behavior?**
`GVL.changeLanguage` fails in IE 11.
Output is `GVLError: unsupported language en`
The [screenshot](https://www.dropbox.com/s/cgw28re97p0gvfb/screenshot%202020-08-12%2014.46.46.png?dl=0) may or may not say more. Living example, if needed, can be seen on the website [horoskopy.cz](https://horoskopy.cz/) when you type `scmp.open()` into the console.

Thanks,
Jonas, Seznam.cz

**Comment by chrispaterson** [comment]
Hi @jonas-veselka are you using some form of Polyfill? Because the library is no polyfilled to handle IE 11 at this point.

**Comment by jonas-veselka** [comment]
Hi @chrispaterson, thanks for Your reply.
We use few core-js polyfills. We are forced to keep the app size low, so we use only the ones we actually need.
Unless You have a tip, which feature do I need to polyfill, I'll try to analyze [the core code](https://github.com/InteractiveAdvertisingBureau/iabtcf-es/blob/2b1459bf2a8fdc4b5d4a9c8367b2e8d87986a795/modules/core/src/GVL.ts#L412), and hopefully find which one it is. I will let You know.

**Comment by chrispaterson** [comment]
I'm not sure exactly @jonas-veselka I just know that the GVL.consentLanguages wraps a `Set` instance.  That error is thrown only if the language (as uppercase) isn't in the set.  But I also see that IE 11 should have support for Set.has() https://caniuse.com/#feat=mdn-javascript_builtins_set_has 

I work on a Mac so I haven't really tested IE 11.  Do you know how I could test this?

**Comment by chrispaterson** [comment]
Also, can you provide the code that triggers this error?

**Comment by jonas-veselka** [comment]
Hi,
the triggering code is simply something like this:
```
const DEFAULT_LANGUAGE = 'cs';

GVL.baseUrl = VENDORS_BASE_URL;
const gvl = new GVL();
await gvl.readyPromise;
gvl.changeLanguage(DEFAULT_LANGUAGE);
```

The problem was indeed in polyfills. We were using **[Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) and [Set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) polyfills** in a wrong way – importing later then this part of code was running. Map and Set have only partial support in IE 11. `.has` is OK, but there are other unsupported methods but now I'm not able to say which ones are used by this.

So, I can close this issue now. Sorry for bothering and thanks for Your helpfulness.
