### ISSUE TITLE
Typo for `*LegitimateInterest` documentation

### ISSUE THREAD

**Issue by dustingibbs** [InteractiveAdvertisingBureau/iabtcf-es#209]
All docs referring to `*LegitimateInterest` are missing trailing `s`

- vendorLegitimateInterest
- purposeLegitimateInterest
- publisherLegitimateInterest
- publisherCustomLegitimateInterest

github docs:
https://github.com/InteractiveAdvertisingBureau/iabtcf-es/tree/master/modules/core#vectors

and here:
https://iabtcf.com/api/core/classes/tcmodel.html#vendorlegitimateinterest

**Comment by chrispaterson** [comment]
Those API docs are defunct right now... I'm working on re-writing them.
