### ISSUE TITLE
Object is not iterable error in IE 11 with @babel-plugin-transform-runtime

### ISSUE THREAD

**Issue by mghouse036** [InteractiveAdvertisingBureau/iabtcf-es#213]
**Version**
Upgrading lib from **1.1.0-3** to **1.1.0-6**

**Module (core, cmpapi, cli, stub, or testing)**
Core

**Describe with reproduction steps **
Hi @chrispaterson , 
I tried poly-filling the latest tcf core library with babel runtime, But facing **Object not iterable** exception due the destructing for..of syntax ES syntax used in core lib with the below commit:
https://github.com/InteractiveAdvertisingBureau/iabtcf-es/commit/814550087e2d9faa3eeaeed5e96d646536c66e.

_Can we move back to forEach syntax at all places, since this was working in 1.1.0-3 version with forEach syntax_.

**Runtime config:**
![image](https://user-images.githubusercontent.com/26306579/90787171-10e41e00-e322-11ea-8297-0328dec652b0.png)

**Error in IE:**
![image](https://user-images.githubusercontent.com/26306579/90785855-78996980-e320-11ea-9ace-7f2a3313e873.png)

**Comment by mghouse036** [comment]
Hi @chrispaterson , 
Is there any update on this issue?

**Comment by chrispaterson** [comment]
Reverted back, in release 1.1.2

**Comment by mghouse036** [comment]
Thanks. Its working now in IE 11.
