### ISSUE TITLE
Support: Setting publisher restrictions on most of the purposes and for all vendors from GVL

### ISSUE THREAD

**Issue by jelenatomcic** [InteractiveAdvertisingBureau/iabtcf-es#214]
Hi Chris,

we need to set publisher restrictions for 7 purposes and for all vendors in GVL.
Here is how I implemented that (just the method for setting publisher restrictions):
```
// ...
  const purposeRestrictions = []
  const restrectedPurposes = [2, 5, 6, 7, 8, 9, 10]

  restrectedPurposes.forEach(el => {
     purposeRestrictions.push(new PurposeRestriction(el, RestrictionType.REQUIRE_CONSENT))
  })
  for (let i = 0; i < purposeRestrictions.length; i++) {
     allVendors.forEach(vendor => {
     tcModel.publisherRestrictions.add(vendor.id, purposeRestrictions[i])
  })
// ...
```
Is this the right way to implement the requirement I described above?

Resulting TCString is huge, but when decoded, resulting TCModel has 7 publisher restrictions of the REQUIRE_CONSENT type. Is there a way to see for which vendors are those applied?

In the documentation I found only this example:
```
import {TCModel, PurposeRestriction, RestrictionType} from '@iabtcf/core';

// first you must create a PurposeRestriction
const purposeRestriction = new PurposeRestriction();

purposeRestriction.purposeId = 2;
purposeRestriction.restrictionType = RestrictionType.NOT_ALLOWED;

// vendorID and restriction
tcModel.publisherRestrictions.add(2000, purposeRestriction);
```
and similar in the unit test you sent regarding another issue 
https://github.com/InteractiveAdvertisingBureau/iabtcf-es/commit/d2d6857af600cc6b3a72eb360358eba19f176628

Thanks in advance.

Regards,
Jelena

**Comment by chrispaterson** [comment]
Hi Jelena, your implementation is correct.  The IAB is working out a solution for cases where all vendors are restricted the same way by a purpose and the resulting TC string being too large.

**Comment by asr-enid** [comment]
Fix by https://github.com/InteractiveAdvertisingBureau/iabtcf-es/pull/244 once merged

**Comment by shortaflip** [comment]
Pull Request #244 that addressed this enhancement has been merged in to a pre-release v1.2.1-1 of the library.  This will stay in a pre-release state for two weeks unless issues with the pre-release are found.

**Comment by shortaflip** [comment]
v1.2.1-2 of the library has been pre-released.  If all goes well by this day next week, v1.2.1 of the library which contains the changes for this issue will be released.

**Comment by shortaflip** [comment]
v1.2.1-3 of the library has been pre-released.  There were some request yesterday to add two more PRs (230 & 246).  While the PRs should not have any problems, if within a week time any bug from either one is found, I will revert those merges and assign them to the next release.  This way we can get the changes that were originally in queue for 1.2.1 released and have no more delays.

**Comment by shortaflip** [comment]
v1.2.1 of the library that contains the changes from the PR that closed this ticket is live.
