### ISSUE TITLE
Allow custom tcData object properties in payload for event listeners

### ISSUE THREAD

**Issue by warrensavich** [InteractiveAdvertisingBureau/iabtcf-es#215]
Apologies if this has already been addressed, how can I modify the tcData object to add custom properties (such as addtlConsent) for callbacks subscribed as event listeners via addEventListener? 

That would be an excellent feature to add if it doesn't exist already.

**Comment by chrispaterson** [comment]
Hi @warrensavich , this feature is in the current pre-release version 1.1.0.  You would create a custom command with the same name as the built-in command and your custom command will be called before responding to requests from calling page scripts.  Details are here: https://github.com/InteractiveAdvertisingBureau/iabtcf-es/tree/master/modules/cmpapi#built-in-and-custom-commands
