### ISSUE TITLE
Language code TR (Turkish) results in TCMODEL error: GVLError: unsupported language TR

### ISSUE THREAD

**Issue by HeinzBaumann** [InteractiveAdvertisingBureau/iabtcf-es#219]
**Version**
1.1.0-3

**Module (core, cmpapi, cli, stub, or testing)**
core/cmpapi

**Describe with reproduction steps – What is the expected behavior?**
Language code TR (Turkish), which is a officially supported IAB language, results in TCMODEL error: GVLError: unsupported language TR.

You can reproduce this using this site: https://test.quantcast.mgr.consensu.org/tcfv2/index.html?coreConfig.lang_=%22tr%22.

I haven't looked into the TCFAPI library yet, my guess is that there is a list of languages supported and TR is not listed. (I believe that TR was a recent addition to TCF.

**Comment by HeinzBaumann** [comment]
I checked the code base. ConsentLanguages.ts the ConsentLanguage object is missing TR.

**Comment by chrispaterson** [comment]
Fixed in version 1.1.1
