### ISSUE TITLE
Events are not triggered in addEventListener() after update() in invoked with uiVisible=false

### ISSUE THREAD

**Issue by theOnlyBoy** [InteractiveAdvertisingBureau/iabtcf-es#220]
**Version**
1.1.0-6

**Module (core, cmpapi, cli, stub, or testing)**
cmpapi, stub

**Describe with reproduction steps – What is the expected behavior?**
After the first update of `CmpApi` with flag `uiVisible=false` there is `tcloaded` event triggered as expected. Although all following updates with any `uiVisible` value do not fire any events in `addEventListener` method.

**Example:**
```
window.__tcfapi('addEventListener', 2, (tcData) => console.log(tcData.eventStatus));
let tcString = 'CO5dPi4O5dPx2B7DvCENA2CgAAAAAAAAAAAAGewAAM8gAAAA.YAAAAAAAAAAA';
let cmpApi = new CmpApi(CMP_ID, CMP_VERSION, IS_SERVICE_SPECIFIC);
cmpApi.update(tcString, false); // tcloaded is triggered
cmpApi.update(tcString, true); // nothing happens
cmpApi.update(tcString, false); // nothing happens
```

**Comment by chrispaterson** [comment]
I can't reproduce this in a test.  Maybe you can give me more of your surrounding use case?

**Comment by theOnlyBoy** [comment]
@chrispaterson After investigating more precisely I might admit that it's our issue and it's not related to CmpApi itself. I'm sorry and thank you for your time! Unfortunately, there is another issue that happens in case we fix this one: extra event `useractioncomplete` is fired in case of calling multiple times with `uiVisible=false`. As I see you're working on the issue already here: https://github.com/InteractiveAdvertisingBureau/iabtcf-es/issues/137

Thank you for your efforts!
