### ISSUE TITLE
How to add addtlConsent - Google's Additional Consent String (AcString)

### ISSUE THREAD

**Issue by adityamishraofficial** [InteractiveAdvertisingBureau/iabtcf-es#223]
I want to add **addtlConsent** String into My tcModel, But I am getting issue while adding this,

  ```
        this.gvlString = GVL.baseUrl = configData.config.vendorListUrl;
        this.gvl = new GVL(configData.config.vendorFileVersion);
        this.tcModel = new TCModel(this.gvl);
        this.tcModel.cmpId = configData.config.cmpId ? configData.config.cmpId : gdprVersion.cmpId;
        this.tcModel.cmpVersion = configData.config.cmpVersion ? configData.config.cmpVersion : gdprVersion.cmpId;
        this.tcModel.addtlConsent = 'This is my ac string';
```

I could not found any documentation for this, Please help me to add AcString

**Comment by chrispaterson** [comment]
Hi @adityamishraofficial, addtlConsent can be added to the @iabtcf/cmpapi libarary by adding a custom command that overrides the 'getTCData' command.  https://github.com/InteractiveAdvertisingBureau/iabtcf-es/tree/master/modules/cmpapi#built-in-and-custom-commands

The TCF doesn't officially support Google's transitional addtlConsent property.
