### ISSUE TITLE
IE11 "Symbol" not defined in Vector.js (1,2174)

### ISSUE THREAD

**Issue by fcostantino** [InteractiveAdvertisingBureau/iabtcf-es#224]
**Version**
IE11 11.1082.18362

**Module (core, cmpapi, cli, stub, or testing)**
core

**Describe with reproduction steps – What is the expected behavior?**
When the core loads on IE 11 i get the error in object . Does your library works on IE11 ?

**Comment by chrispaterson** [comment]
hi @fcostantino, no it does not support IE 11 out of the box, you'll need to polyfill the library to make it work.  I'm working on making that easier in #132
