### ISSUE TITLE
Built in Custom Commands are invoked with wrong parameters if callback throws exception

### ISSUE THREAD

**Issue by matita** [InteractiveAdvertisingBureau/iabtcf-es#225]
**Version**
`1.1.0-6`

**Module (core, cmpapi, cli, stub, or testing)**
`cmpapi`

**Describe with reproduction steps – What is the expected behavior?**
Code to reproduce the issue:
```js
import { CmpApi } from '@iabtcf/cmpapi';

const api = new CmpApi(123, 456, true, {
  addEventListener: (next, tcData, success) => {
    if (tcData) {
      tcData.someProp = 'some value';
    }

    if (typeof next === 'function') {
      next(tcData, success);
    } else {
      console.error('next is not a function');
    }
  },
});

api.update('', false);

window.__tcfapi('addEventListener', 2, (tcData, success) => {
  console.log('before exception', tcData, success);
  throwExceptionWithNonExistingFunction();
  console.log('after exception', tcData, success);
});
```

Current behaviour:
- `next is not a function` is logged

Expected behaviour (which is what happens if no built-in custom command is specified):
- `before exception {...} true` is logged
- `before exception null false` is logged
- `Uncaught ReferenceError: throwExceptionWithNonExistingFunction is not defined` error is logged

Considerations:
1. TCF API spec does not define what should be the behaviour in case the `__tcfapi` callback throws exception, currently the callback is invoked twice: first with right `tcData` and `success === true`, then with null `tcData` and `success === false`. It makes sense but the side effect is that the callback is invoked twice, maybe there should be some official spec on how `__tcfapi` should behave in case of callback's exception, or at least specify that it's up to the consumer to `try...catch` the callback as the `__tcfapi` behaviour could not be reliable in case of exceptions
2. I think built-in custom commands should always be invoked with `next` as a function, we have another similar case where they are invoked with only `tcData` and `success` as parameters, which I guess this PR should solve: https://github.com/InteractiveAdvertisingBureau/iabtcf-es/pull/212 (e.g. `__tcfapi('getTCData', 2, function(tcData, success) {}, null)`)
3. this should be the code that exposes the issue: https://github.com/InteractiveAdvertisingBureau/iabtcf-es/blob/b4152095ebc3b494d5e69aebf32c608b6a6ecf4d/modules/cmpapi/src/command/Command.ts#L22-L30

**Comment by matita** [comment]
Actually about, Considerations.1, TCF spec says:

> The `callback` shall be invoked only once per api call with this command.

when describing `getTCData` command https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20CMP%20API%20v2.md#gettcdata (at the end of the paragraph).

So probably it should not be invoked twice when it throws exception.

**Comment by chrispaterson** [comment]
@matita I think this actually has to do with the `addEventListener` command because it's slightly different.  `addEventListener` utilizes `getTCData` command, so I would write the custom command there.

**Comment by chrispaterson** [comment]
I put in a patch release to throw an error when removeEventListener and addEventListener are attempted to be overwritten and [wrote a note in the README](https://github.com/InteractiveAdvertisingBureau/iabtcf-es/tree/master/modules/cmpapi#built-in-and-custom-commands).

**Comment by matita** [comment]
@chrispaterson actually I have the same issue with `getTCData`, also if I don't specify a custom `addEventListener` the custom property is not added, and that would be very bad for Google's support.
You can see both issues here: https://runkit.com/embed/qrdcayhdfs9v

**Comment by raquelyustemrf** [comment]
We are experimenting the same problem as @matita 

When there is an error on `getTCData` (for example, it's called with `null` in the fourth parameter) the custom command receives the first parameter (next) as `null` and the second one (tcData) as `false`. 

In preview versions, the first parameter was the callback function and the second one was `null`. Is this the expected behavior? Because we cannot call the callback anymore in this cases, we experiment an error like `next is not a function`.

**Comment by matita** [comment]
@chrispaterson I might be wrong, but I think it would just be a matter of changing this code:
https://github.com/InteractiveAdvertisingBureau/iabtcf-es/blob/b4152095ebc3b494d5e69aebf32c608b6a6ecf4d/modules/cmpapi/src/command/Command.ts#L35-L55

into this code:
```js
  protected invokeCallback(response: any): void {

	const success = response !== null;

    if (typeof this.next === 'function') {

      this.callback(this.next, response, success);

    } else {

      this.callback(response, success);

    }

  }
```

**Comment by shortaflip** [comment]
v1.2.1-3 of the library has been pre-released, which contains the changes submitted with this issues accompanying PR.  Please try out the pre-release in your environments so that we can confirm the stability in time for the actual release next week on Tues.  Let me know if any bugs from this ticket are found so that I can push these changes to a different release and verify that v1.2.1 without these changes are stable.  Thank you.

**Comment by shortaflip** [comment]
v1.2.1 of the library that contains the changes from the PR that closed this ticket is live.
