### ISSUE TITLE
Unable to enhance addEventListener command response in 1.1.4

### ISSUE THREAD

**Issue by TUNER88** [InteractiveAdvertisingBureau/iabtcf-es#227]
**Version**: 1.1.4
**Module:** cmpapi

Version `1.1.4` makes impossible to enhance `addEventListener` callback response with [Googles AC string ](https://support.google.com/admanager/answer/9681920?hl=en)

Overriding the command with custom function is now failing with following message:
`Error: Built-In Command for addEventListener not allowed: use getTCData instead`.
This was working in `1.1.3`!

By seeing this error, I would expect that customised `getTCData` response will be reused for `addEventListener` as well, but this is unfortunately not the case 😞 

<details>
<summary>Error on overriding addEventListener</summary>
<img width="792" alt="Screenshot 2020-10-14 at 13 39 34 (1)" src="https://user-images.githubusercontent.com/1565397/95992528-54449f80-0e2e-11eb-8402-3574d0ce544d.png">
</details>

<details>
<summary>Response for getTCData and addEventListener is not equal</summary>
<img width="723" alt="Screenshot 2020-10-14 at 15 02 26" src="https://user-images.githubusercontent.com/1565397/95992530-5575cc80-0e2e-11eb-8bfe-3ca55e6f1ce9.png">
</details>

**Comment by raquelyustemrf** [comment]
We are experimenting the same problem here, seems like `addEventListener` doesn't utilize `getTCData` to retrieve the tcData object.

**Comment by opencmp** [comment]
@chrispaterson Hi Chris, could you please check on this? It is a breaking change that makes a lot of trouble and as long as this is not solved we can"t upgrade to newer versions.

**Comment by res-io** [comment]
@chrispaterson Any updates on this issue? We are also waiting for a fix and are stuck on the upgrade path.

**Comment by TUNER88** [comment]
Hey @InteractiveAdvertisingBureau, is this package still maintained, or is it already abandoned?

**Comment by resolution-afk** [comment]
We waiting as well. Can you give an update?

**Comment by shortaflip** [comment]
PR #234 has been merged in, closing this issue.

**Comment by TUNER88** [comment]
@shortaflip when can we expect a stable version with this fix?
`1.1.4` - is broken
and `1.2.1-0` is unstable, at least according to semver it prefixed as pre-release.

**Comment by shortaflip** [comment]
@TUNER88 Hi, the release candidate is currently waiting on one more PR that fixes some failing tests that were introduced by some of the PRs committed.  Once that is finished I'll create a new pre-release that will contain the new changes including the one for this issue.  If no issues are found in the pre-release, it will be considered stable and will be released.  I haven't done this pre-release to release process so best estimate I can give is 1 week to 2 weeks at the latest.

**Comment by TUNER88** [comment]
@shortaflip cool, thanks for keeping us updated.
I would be cool if could give next pre-releases a correct tag, since the `1.2.1-0` is tagged as `latest`, which is the default tag for stable versions. So no everyone who is now running `npm i @iabtcf/cmpapi` will get an unstable version.

**Comment by shortaflip** [comment]
@TUNER88 ooooffff, that is my bad.  I just edited the dist-tags for the libs repos.  `latest` should be back to 1.1.4 and pre-release has been tagged as `next`.

**Comment by TUNER88** [comment]
@shortaflip great, thanks 👍

**Comment by shortaflip** [comment]
Pull Request #234 that addressed this enhancement has been merged in to a pre-release v1.2.1-1 of the library.  This will stay in a pre-release state for two weeks unless issues with the pre-release are found.

**Comment by TUNER88** [comment]
Hey @shortaflip, two weeks are over, when can we expect the stable release?

**Comment by shortaflip** [comment]
Hi @TUNER88,

A bug was filed with a PR and is currently being deliberated as to whether it should be included in the v1.2.1 release.
* issue [here](https://github.com/InteractiveAdvertisingBureau/iabtcf-es/issues/261).
* pr [here](https://github.com/InteractiveAdvertisingBureau/iabtcf-es/pull/262).

**Comment by shortaflip** [comment]
v1.2.1-2 of the library has been pre-released.  If all goes well by this day next week, v1.2.1 of the library which contains the changes for this issue will be released.

**Comment by shortaflip** [comment]
v1.2.1-3 of the library has been pre-released.  There were some request yesterday to add two more PRs (230 & 246).  While the PRs should not have any problems, if within a week time any bug from either one is found, I will revert those merges and assign them to the next release.  This way we can get the changes that were originally in queue for 1.2.1 released and have no more delays.

**Comment by shortaflip** [comment]
v1.2.1 of the library that contains the changes from the PR that closed this ticket is live.

**Comment by TUNER88** [comment]
@shortaflip great, thanks for the update 👍
