### ISSUE TITLE
CmpApi: Can't override addEventListener

### ISSUE THREAD

**Issue by opencmp** [InteractiveAdvertisingBureau/iabtcf-es#229]
Starting from cmpapi@1.1.4, the api "addEventListener" must not be overriden anymore. This breaks our CMP which adds custom properties to the return value like "addtlConsent" (Google Vendors) and others which the publishers rely on. If this is not possible any more the API changes on publisher side. It is a big deal to tell all publishers to switch to another API.

What is the reason for this breaking change and is it really neccessary? It not only involves changes on CMP side but also on all publishers side.

We really hope this restriction can be removed.

**Comment by TUNER88** [comment]
I've already reported this issue here: #227 
But there is unfortunately no feedback from IAB so far 😞

**Comment by shortaflip** [comment]
PR #234 has been merged in, closing this issue

**Comment by shortaflip** [comment]
Pull Request #234 that addressed this enhancement has been merged in to a pre-release v1.2.1-1 of the library.  This will stay in a pre-release state for two weeks unless issues with the pre-release are found.

**Comment by shortaflip** [comment]
v1.2.1-2 of the library has been pre-released.  If all goes well by this day next week, v1.2.1 of the library which contains the changes for this issue will be released.
