### ISSUE TITLE
@iabtcf/core: Remove typescript and global from dependencies

### ISSUE THREAD

**Issue by midudev** [InteractiveAdvertisingBureau/iabtcf-es#233]
I would like to see `typescript` moved from `dependencies` to `devDependencies` so `typescript` is not installed on every project that's using this package. This dependency alone is taking 50mb of disk space and causing a major slow down over Travis CI against the version without @iabtcf/core.

Also, `global` dependency seems to not be used anywhere as well but it's being installed.

**Comment by dmdabbs** [comment]
@shortaflip is this issue something to consider?

**Comment by shortaflip** [comment]
@dmdabbs Yes but I'd like this to be considered in the next release instead, so I have the proper amount of time to look through it.

**Comment by chrispaterson** [comment]
Agree. Typescript is listed twice for some reason. This library has no ‘dependencies’

**Comment by midudev** [comment]
Just to push this a little bit. :)

Biggest dependency installed:
![image](https://user-images.githubusercontent.com/1561955/116250522-1544be80-a76e-11eb-85fd-21f7e83762cb.png)

Installed because it's present in the package.json of...
![image](https://user-images.githubusercontent.com/1561955/116250603-24c40780-a76e-11eb-87a9-b6b635aafac8.png)

If we could move this... it would be nice in order to improve space used of installation.

**Comment by dmdabbs** [comment]
Hello @midudev . @shortaflip and the team wanted to get the essentials into this library release. We can incorporate this into a subsequent release.

**Comment by chrispaterson** [comment]
Just saying, all you have to do is delete the line in the package.json

**Comment by shortaflip** [comment]
Hi guys,

This issue will be a part of the 1.2.2 release as well as the current pending PRs.  I won't be able to attend to this issue or the current pending PRs for a couple of weeks at least since I have internal work that I need to do.

If anyone makes a PR before then, great, otherwise I will address it in a couple of weeks.

**Comment by shortaflip** [comment]
PR for this issue: #290

**Comment by shortaflip** [comment]
iabtcf-es library pre-release v1.3.0-2 is live.  The pre-release will be out for about one week so that the new changes can be used in your environments.  If no problems are found the pre-release will transition to release v1.3.0.
