### ISSUE TITLE
gvl.vendors differ from gvl.getJson().vendors

### ISSUE THREAD

**Issue by alextremp** [InteractiveAdvertisingBureau/iabtcf-es#235]
**Version**

From 1.1.x

**Module (core, cmpapi, cli, stub, or testing)**

core

**Describe with reproduction steps – What is the expected behavior?**

- As GVL describes, `gvl.vendors` and `gvl.getJson().vendors` should be the same if `narrowVendorsTo` has not been called : 

```
 /**
   * vendors
   *
   * @return {IntMap<Vendor>} - the list of vendors as it would on the JSON file
   * except if `narrowVendorsTo` was called, it would be that narrowed list
   */
  public get vendors(): IntMap<Vendor>
```

- But if we use the `gvl.getJson().vendors` to be shown to an user in a TCF UI, there are some vendors that will not be encoded because `gvl.getJson().vendors` are the `gvl.fullVendorList` but to encode the TCString, the `gvl.vendors` are being used, with missing vendors from the full vendor list. 
> This is surely caused by the vendors reduction and replacement after the first vendors assignment in the `GVL` class.

This behavior can be reproduced with this snippet:

```
GVL.baseUrl = VENDOR_LIST_ENDPOINT // to be replaced by yours

const logMissingVendors = async gvlVersion => {
    const gvl = new GVL(gvlVersion)
    await gvl.readyPromise

    const gvlJson = gvl.getJson()

    const rawVendors = gvl.vendors
    const jsonVendors = gvlJson.vendors

    const removed = Object.keys(jsonVendors).filter(
      key => !rawVendors.hasOwnProperty(key)
    )
    console.log('missing vendors v' + gvlVersion, removed)
}

await logMissingVendors(36)
await logMissingVendors(62) // current latest
```

That snippet will output:

```
missing vendors v36 [ '612' ]

missing vendors v62 [
  '9',   '51',  '408',
  '409', '520', '648',
  '653', '675', '722',
  '813'
]
```

**Comment by alextremp** [comment]
Ah, now I've seen that those vendors have a deletedDate and vendors reduction is skipping them for that reason, closing the issue 👍

**Comment by kyrylenko** [comment]
@alextremp you saved my time, thanks :)
