### ISSUE TITLE
Language code EU (Euskera) results in TCMODEL error: GVLError: unsupported language EU

### ISSUE THREAD

**Issue by FeelHippo** [InteractiveAdvertisingBureau/iabtcf-es#238]
Version
1.1.4

Module (core, cmpapi, cli, stub, or testing)
core/cmpapi

Describe with reproduction steps – What is the expected behavior?
Language code EU (Euskera), is not yet included in ConsentLanguages.ts, hence results in TCMODEL error: GVLError: unsupported language EU.

Can you please add that to your list, and a number of our clients are required to have their cmp translated into Euskera. 
Thank you in advance.

**Comment by dmdabbs** [comment]
Hello @FeelHippo . The IAB Europe does not support that language. See https://register.consensu.org/Translation. You should reach out to them to add support. Once they officially support it then this community library would add support.
