### ISSUE TITLE
Missing variable in example

### ISSUE THREAD

**Issue by mindplay-dk** [InteractiveAdvertisingBureau/iabtcf-es#251]
There's an example here with an undeclared variable `success`:

https://github.com/InteractiveAdvertisingBureau/iabtcf-es/blob/master/modules/cmpapi/README.md#custom-commands

```js
const songLyricCallback = (lyrics) => {

  if(success) { // <--- ERROR: undefined variable "success"

    console.log(lyrics)

  } else {

    console.error('Error: could not get song lyrics')

  }

}
```

(I'm not sure how to correct the example.)

**Comment by dmdabbs** [comment]
Hello @mindplay-dk . This is the project repo for the TCF es open source community maintained library code. Would you mind transferring this issue to the Issues list on the TCF Specification repo at https://github.com/InteractiveAdvertisingBureau/iabtcf-es/issues?

**Comment by mindplay-dk** [comment]
> Would you mind transferring this issue to the Issues list on the TCF Specification repo at https://github.com/InteractiveAdvertisingBureau/iabtcf-es/issues?

Uhm. That's where we are? 😄

**Comment by dmdabbs** [comment]
Oh, apologies, @mindplay-dk! Here is the TCF specification GitHub repo
[https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework)

**Comment by mindplay-dk** [comment]
I'm sorry, but I'm still confused. The error is in the example in _this_ repository.

**Comment by dmdabbs** [comment]
You're right Rasmus. My apologies for not reading thoroughly and assuming that a sample code was a reference to samples in the specs where we've had inaccuracies in the past. I'm not familiar with this custom callbacks feature so will have to defer to someone who is.

**Comment by shortaflip** [comment]
PR #291

**Comment by shortaflip** [comment]
iabtcf-es library pre-release v1.3.0-2 is live.  The pre-release will be out for about one week so that the new changes can be used in your environments.  If no problems are found the pre-release will transition to release v1.3.0.
