### ISSUE TITLE
Compliance with policy check 26 (Device Storage Duration & Access Disclosure) only possible with unstable package versions

### ISSUE THREAD

**Issue by jankarres** [InteractiveAdvertisingBureau/iabtcf-es#263]
**Version** 1.1.4
**Module (core, cmpapi, cli, stub, or testing)** All

**Describe with reproduction steps – What is the expected behavior?**

The TCF Compliance Team emailed us that policy check 26 (Device Storage Duration & Access Disclosure) from the TCF v2.1 technical specification is mandatory to be implemented by all (new) CMPs for TCF certification.

We develop our CMP in TypeScript, which made us notice that version 1.1.4, the last stable version (e.g. https://www.npmjs.com/package/@iabtcf/core?activeTab=versions), of all packages does not yet meet the requirements of policy check 26. For example, the `@iabtcf/core/lib/model/gvl/Vendor.d.ts` do not have the required `deviceStorageDisclosureUrl` property.

You published version 1.2.1-1 as unstable (next) version on NPM, which is the latest version that support the required features.

Why are we forced to use an unstable/beta version of your package to comply for the certification of a production CMP? We think for a mandatory requirement CMPs should not be forced to use unstable versions.

**Comment by shortaflip** [comment]
Hello @jankarres,

1.2.1-1 is a prerelease version that is a release candidate for v1.2.1 (next stable version).  It is marked as (unstable) in npm to show that it is going through testing.  In all likelihood it will change from prerelease to actual release in the next week or so if everything goes well with PR 262.

Please let me know if you have any more questions otherwise I will close this issue at end of day.

**Comment by shortaflip** [comment]
v1.2.1-2 of the library has been pre-released.  If all goes well by this day next week, v1.2.1 of the library which contains the changes for this issue will be released.

**Comment by jankarres** [comment]
Why has this ticket been closed while there is still no stable version to comply with policy check 26 as CMP, @shortaflip?

**Comment by dmdabbs** [comment]
Hello @jankarres . Kevin commented three days ago that there is a pre-release lib that addresses this issue and that it should be released early next week.
