### ISSUE TITLE
Vendors declaring special purposes only are not encoded properly in LI signal

### ISSUE THREAD

**Issue by jcmlmorav** [InteractiveAdvertisingBureau/iabtcf-es#288]
**Version**
v1.2.1

**Module**
Core

**Description**
When we have vendors only declaring special purposes like vendor 953, when the CMP send the LI signal for it then the encoder should be allow these vendors to be encoded

<pre>
  953: {
    id: 953,
    name: "adbalancer Werbeagentur GmbH",
    purposes: [ ],
    legIntPurposes: [ ],
    flexiblePurposes: [ ],
    specialPurposes: [
      2
    ],
    features: [ ],
    specialFeatures: [ ],
    policyUrl: "https://www.adbalancer.com/datenschutz",
    cookieMaxAgeSeconds: null,
    usesCookies: false,
    cookieRefresh: false,
    usesNonCookieAccess: false
  }
</pre>

**Current behavior**
SemanticPreEncoder.ts has validations to not allow vendors to be set in LI/Consent section if the vendor did not has legitimate purposes/Consent purposes declared, so the vendor is not being set in the Legitimate Interest vector

**Expected behavior**
SemanticPreEncoder.ts should encode in the LI section the vendors declaring only special purposes as they have no right to object

**Comment by dmdabbs** [comment]
Hello/Hola Juan.
Thank you for posting this issue and especially for also posting a PR. Many people raise issues, but few offer a solution.

The IAB Europe is aware of the issue. The library's current handling/encoding was in line with the TCF Policies.  IAB listened to community feedback and recently amended the Technical Spec to permit the encoding you propose. You can see the official notice here: [https://iabeurope.eu/cmp-vendor-notifications/](https://iabeurope.eu/cmp-vendor-notifications/). 

The folks in the community who contribute to library releases intend to get a version out as soon as possible.  We'll review your PR. 

cc: @shortaflip, @a2intl, @alextcone

**Comment by shortaflip** [comment]
Closed by PR #289
