### ISSUE TITLE
removeEventListener callback is called with null if tcData is enriched.

### ISSUE THREAD

**Issue by anas7asia** [InteractiveAdvertisingBureau/iabtcf-es#296]
**Version**

Problem is encountered in v1.3.0 and v1.2.1. Worked fine in 1.1.4.
 
**Module (core, cmpapi, cli, stub, or testing)**

cmpapi

**Issue**

`removeEventListener` callback is called with `null` instead of a boolean if `tcData` is enriched. 

It works as expected if `tcData` is not enriched.

**Reproduction steps**

1. Create a CMP:
```js
const cmpApi = new CmpApi(CMP_PROVIDER_ID, CMP_VERSION, true, {
  'getTCData': (next, tcData, success) => {
    tcData.reallyImportantExtraProperty = true; // this causes the problem
    next(tcData, success);
  }
})
```

2. Invoke `init` command. CMP works fine.

3. Invoke `addEventListener` and `removeEventListener` commands:
```js
const callback = (tcData, success) => {
  if(success) {
    __tcfapi('removeEventListener', 2, (removed) => {
      if(removed) {
        // Never passes the condition, <removed> value is always null
      }
    }, tcData.listenerId);
  } else {}
}

__tcfapi('addEventListener', 2, callback);
```

4. `removed` parameter is always `null` ❌ 

**What is the expected behavior?**

According to [the specs](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20CMP%20API%20v2.md#removeeventlistener) `removeEventListener` callback should be called with a boolean. 

<br>
Thank you!

**Comment by shortaflip** [comment]
Hi @anas7asia, I tried reproducing it with v1.3.0 of the cmpapi but I am getting a boolean instead of the expected null value.  Note that the boolean value is returned regardless of manipulation of the tcData.

<img width="423" alt="Screen Shot 2021-08-05 at 12 04 29 PM" src="https://user-images.githubusercontent.com/23621173/128420391-776d1d16-4d91-45aa-a491-584ef6eb3194.png">

Any steps that you did that I might be missing?

This might also help, this [issue](https://github.com/InteractiveAdvertisingBureau/iabtcf-es/issues/227) solved by this [PR](https://github.com/InteractiveAdvertisingBureau/iabtcf-es/pull/234), did make it so that your custom `getTCData` function is also called by the `addEventListener` and `removeEventListener` commands.  This was merged in v1.2.1 of the cmpapi library.

**Comment by anas7asia** [comment]
Hello @shortaflip, thank your for your answer!

I've tried to [reproduce](https://stackblitz.com/edit/js-ybzidj?file=index.js) the issue in a pristine project. This time I'm getting an error instead of a `null` parameter, but it seems it can be linked to the submitted issue. 

Or maybe I miss something in the installation process?

### Installation

I provide a custom `getTCData` command. 

```js
import { CmpApi } from '@iabtcf/cmpapi'; // v1.3.0

const cmpApi = new CmpApi(1000, 1, true, {
  getTCData: (next, tcData, success) => {
    console.log('>>> getTCData > next:', next);
    console.log('>>> getTCData > tcData:', tcData);
    console.log('>>> getTCData > success:', success);
    tcData.reallyImportantExtraProperty = true;
    next(tcData, success);
  }
});
```

Then activate the CMP:

```js
cmpApi.update('CPKgliIPKgl6FPoABAENBeCgAAAAAAAAAAqIAAAAAAAA.YAAAAAAAAAAA', false)
```

Then invoke `addEventListener`  + `removeEventListener` commands:

```js
__tcfapi('addEventListener', 2, (tcData, success) => {
  if (success) {
    __tcfapi(
      'removeEventListener',
      2,
      removed => { console.log('removed:', removed); },
      tcData.listenerId
    );
  }
});
```



### Usage

As you have mentioned, custom `getTCData` function is also called by the `addEventListener` and `removeEventListener` commands. And the logs do confirm this.

If `tcData.reallyImportantExtraProperty = true;` is not included in `getTCData` I get the logs twice and everything is fine:

1. first `getTCData` call (addEventListener)

   ```
   >>> getTCData > next: (tcData, success) => { if (success) { __tcfapi('removeEventListener', …
   >>> getTCData > tcData: t {cmpId: 1000, cmpVersion: 1, eventStatus: "tcloaded", …
   >>> getTCData > success: true
   ```

2. second `getTCData` call (removeEventListener)

   ```
   >>> getTCData > next removed => { console.log('removed:', removed); }
   >>> getTCData > tcData true
   >>> getTCData > success true
   removed: true
   ```

---

If `tcData.reallyImportantExtraProperty = true;` is present in `getTCData` I get

1. first `getTCData` call (by addEventListener)

   ```
   >>> getTCData > next: (tcData, success) => { if (success) { __tcfapi('removeEventListener', ...}
   >>> getTCData > tcData: t {cmpId: 1000, cmpVersion: 1, eventStatus: "tcloaded", …}
   >>> getTCData > success: true
   ```

2. second `getTCData` call (by removeEventListener)

   ```
   >>> getTCData > next: removed => { console.log('removed:', removed); }
   >>> getTCData > tcData: true
   >>> getTCData > success: true
   ```

3. third `getTCData` call (by whom?). tcData is `null` and success is `false` ⚠️

   ```
   >>> getTCData > next: removed => { console.log('removed:', removed); }
   >>> getTCData > tcData: null
   >>> getTCData > success: false
   ```

4. fourth `getTCData` call (by whom?). tcData is `null` and success is `false` ⚠️

   ```
   >>> getTCData > next: (tcData, success) => { if (success) { __tcfapi('removeEventListener', ...}
   >>> getTCData > tcData: null
   >>> getTCData > success: false
   ```

   And since tcData is `null` I get an error:

   ```
   TypeError: Cannot set property 'reallyImportantExtraProperty' of null
       at e.getTCData [as callback]
   ```

---

So it works fine if `tcData` is not manipulated or if `removeEventListener` is not called. But with one of them present, it seems to work incorrectly.

Can you see this error as well? Please, feel free to ask if you need more information.

**Comment by shortaflip** [comment]
Hi @anas7asia, I've been able to replicate what you are seeing.  I will let you know when I have something.

**Comment by shortaflip** [comment]
@anas7asia, so it looks like calls 3 and 4 can be prevented if you check for tcData's type.

* Call 1 `tcData.reallyImportantExtraProperty` is indeed an object and assigning a new value to it is valid.
* Call 2`tcData` is no longer an object but instead a boolean of value `true`.

So for call 2 the code tries to assign `true` to `tcData.reallyImportantExtraProperty` which won't work.  The `getTCData` command then tries to respond, catches the error, invokes the callback with a null arguments, hence calls 3 and 4 with `tcData = null`.

**Comment by anas7asia** [comment]
@shortaflip, everything works fine if I add a check for `tcData`'s type before enriching `tcData` object in the `getTCData` method. Thank you for your help! 🎉

Do you consider this behaviour a bug that can be fixed with a workaround or this is totally intended? If this is intended, maybe it should be mentioned in the documentation? 🙏

**Comment by shortaflip** [comment]
@anas7asia I wouldn't consider this a bug and it is recently committed code so no documentation was made.  I will make a pr for documentation regarding tcData's new behavior with the listener commands and tag you.

**Comment by shortaflip** [comment]
@anas7asia here is PR, just comment if needs more clarification.  Otherwise, I'll find someone that can review it.

**Comment by anas7asia** [comment]
Perfect for me, thank you!

**Comment by shortaflip** [comment]
iabtcf-es library pre-release v1.3.1-0 is live.  The pre-release will stay live for 2 weeks and barring any issues, will then transition to a full release.

**Comment by shortaflip** [comment]
iabtcf-es library v1.3.1 that contains changes that addressed this issue has been released.
