### ISSUE TITLE
Language of GVL not being cloned

### ISSUE THREAD

**Issue by Marco-Prontera** [InteractiveAdvertisingBureau/iabtcf-es#297]
**Version**
Problem is encountered in v1.3.0 and v1.2.1.
**Module (core, cmpapi, cli, stub, or testing)**
Module Core
**Describe with reproduction steps – What is the expected behavior?**
Try building a tcModel and changing the language on the gvl. Call unsetAll on the tcModel and check the language gvl of the tcModel again. Each time it resets the gvl language. 

-> unsetAll should only affect the possible choices that the user can enable or not

Also once changed the language of the gvl shouldn't it be the same for the tcModel?

**Edit:
"unsetAll" is not the cause of the problem but when you go to clone the TCModel.**

**Comment by shortaflip** [comment]
Hi @Marco-Prontera, the language does not seem to be resetting for me.

![Screen Shot 2021-08-05 at 3 01 24 PM](https://user-images.githubusercontent.com/23621173/128427273-32300168-d716-4055-a2c0-b853150b7932.png)

<img width="160" alt="Screen Shot 2021-08-05 at 3 04 37 PM" src="https://user-images.githubusercontent.com/23621173/128427288-0d3324b9-e2a8-4f3b-bd63-699c05aa8d0f.png">

Were there reproduction steps that I might be missing?  Lemme know.

**Comment by Marco-Prontera** [comment]
Yes, sorry. I haven't written a step.
From the TCModel with the language changed, call clone (). And unsetAll on the clone and check the language.
Like this:
        const tcModel = new TCModel(gvl);
        await tcModel.gvl.changeLanguage('fr');
        const cloneTCModel = tcModel.clone();
        cloneTCModel.unsetAll();
And check the language of the cloneTCModel again

**Comment by shortaflip** [comment]
Hi @Marco-Prontera, it looks like the issue lies with the `tcModel.clone()` function.

<img width="302" alt="Screen Shot 2021-08-06 at 1 55 36 PM" src="https://user-images.githubusercontent.com/23621173/128570135-7df7c73a-70d8-448b-b707-653ed69ee3cc.png">

`tcModel.consentLanguage` is cloned properly but `gvl.language` is not cloned properly.  I will investigate and let you know what I find, thank you.

**Comment by shortaflip** [comment]
Hi @Marco-Prontera, I have the PR here: https://github.com/InteractiveAdvertisingBureau/iabtcf-es/pull/306

Check it over and lemme know if you have any concerns, I will find someone from the IAB to review it.

**Comment by Marco-Prontera** [comment]
Hi @shortaflip, only one doubt:
Are we sure that when we change the language, a call is not made again to get the translations? 
Can we test it?

**Comment by shortaflip** [comment]
@Marco-Prontera, I updated the unit test with an assertion for only one call.

**Comment by Marco-Prontera** [comment]
Hi, @shortaflip now it's perfect. Good job! Thank you!

**Comment by shortaflip** [comment]
iabtcf-es library pre-release v1.3.1-0 is live.  The pre-release addresses an issue brought up by this ticket.  Please download and take the pre-release library for a spin.  The pre-release will stay live for 2 weeks and barring any issues, will then transition to a full release.

**Comment by shortaflip** [comment]
iabtcf-es library v1.3.1 that contains changes that addressed this issue has been released.
