### ISSUE TITLE
Documentation on purposeLegitimateInterests seems to conflict 

### ISSUE THREAD

**Issue by rlankhorst** [InteractiveAdvertisingBureau/iabtcf-es#308]
**Version**
1.3.0

**Module (core, cmpapi, cli, stub, or testing)**
core

**Describe with reproduction steps – What is the expected behavior?**
We've had feedback from the IAB that the PurposesLITransparency is not set correctly. The problem is described as:

(seems to have been copied from the docs [here ](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20Consent%20string%20and%20vendor%20list%20formats%20v2.md))

_By default or if the user has exercised their “Right to Object” to a Purpose, the corresponding bit for that Purpose is set to 0. From left to right, Purpose 1 maps to the 0th bit, purpose 24 maps to the bit at index 23. Special Purposes are a different ID space and not included in this field._

As this property is not available in the TCModel, I've assumed that this is the same as purposeLegitimateInterests. 

Following the structure as described here: https://github.com/InteractiveAdvertisingBureau/iabtcf-es/tree/master/modules/core#iabtcfcore

We use TCModel.purposeLegitimateInterests.unset(purposeId) or set() to manage these purposes. 

When looking in the TCModel however, it is not structured as above (index = purposeId-1 and the value is either 1 or 0), but it is structured as an array of purposeId's, where not being in the array is the same as having no consent/false. 

So for an array that would set purpose 1 and 2 to true, and 3 to false, this is described as looking like
```
array(
  0 => 1,
  1 => 1,
  2 => 0,
)
```

But in fact looks like 

```
array(
  0 => 1,
  1 => 2,
)
```

Now the IAB states that our structure should be like in the first array, but is this is not what the documentation [here](https://github.com/InteractiveAdvertisingBureau/iabtcf-es/tree/master/modules/core#iabtcfcore) says, I'm a bit confused here. 

It seems to me that either [this documentation](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20Consent%20string%20and%20vendor%20list%20formats%20v2.md) is wrong, or [this one](https://github.com/InteractiveAdvertisingBureau/iabtcf-es/tree/master/modules/core#iabtcfcore) is wrong. 

Can someone shed some light on this?

**Comment by dmdabbs** [comment]
I can't speak to feedback/direction the IAB has given you. 
As to why you are not seeing any false value displayed, the community decoder at iabtcf.com, at least for Purposes consent and legitimate interest, only bothers to display values that have a positive bit set. But those false values are there since the Purposes consent and LI have 24-bit long sections in the encoded string per the specification. 

cc: nderagakura@iabeurope.eu, @anderagakura

**Comment by rlankhorst** [comment]
Ok, thanks. Looks like we're set 👌

**Comment by dmdabbs** [comment]
Great to hear. Dank je wel for closing, Rogier.  :-)
