### ISSUE TITLE
GVL version 107 broken?

### ISSUE THREAD

**Issue by bogumilkorek** [InteractiveAdvertisingBureau/iabtcf-es#312]
Can someone confirm that GVL version 107 is broken and produces wrong tcString? 

Following tcString decoded as always with GVL version 107 produces 'bitfield encoding length mismatch' error. It seems that every page that uses GVL 107 is affected.

CPMW7URPMW7URF0ACBPLBrCsAP_AAH_AAB5YINNf_X__b3_n-_79__t0eY1f9_7_v-0zjhfdt-8N2f_X_L8X_2M7vF36pr4KuR4ku3bBIQdtHOncTUmx6olVrzPsbk2Mr7NKJ7Pkmnsbe2dYGH9_n93T_ZKZ7______7________________________-_____9__________________-xbHJs_z-qH_Gse23etPoVRYzr2T-EXK9PdtfRP6SNrgp_V0ce4IeQWc9AxgVAgzRzoySA8UCiJKokJALwVKKEiBWwCixUsLQIEbQLbsS4sAhAlINjxqu0yMCZl6uL77zBqLve2wnvrLEqu9_3XGMu8IKFx_TU8HJQggWBkJCwcxwBICXCgAA

**Comment by uc-bsam** [comment]
Do you have details how this tc string was created?
Or any sample code of the tcModel you used if you created it on your own via 
`TCString.encode(tcModel); `

For me it looks like the tcString is "incomplete" and therefore can not be decoded

**Comment by janwinkler** [comment]
A GVL version cannot be broken. If the TC string cannot be read, then only because its written wrong ;-)
