### ISSUE TITLE
Allow bypassing network call when changing language

### ISSUE THREAD

**Issue by Barben360** [InteractiveAdvertisingBureau/iabtcf-es#315]
In our CMP, we are managing the translations of purposes directly in our back-office to allow our customers to rename what they wish.

Therefore, we already have our own system to get translations through the network.

Since [this commit](https://github.com/InteractiveAdvertisingBureau/iabtcf-es/commit/e7480e50bf91b6b47ddf7d3b32a1d12d81a915e2), we have had 404 results occurring when cloning the GVL with a language which is not the default one (EN). For now we made a workaround by hosting the translation files provided by the IAB [here](https://register.consensu.org/Translation) to our CDN, but of course this implies extra cost for us to deliver unused files instead of having a 404.

Would it be possible to be able to disable this automatic call with a boolean parameter or something? Is there already any other workaround?

**Comment by dmdabbs** [comment]
>In our CMP, we are managing the translations of purposes directly in our back-office to allow our customers to rename what they wish.

TCF Policies only permit disclosure of Purposes texts (and the detailed 'legal description') using the official translations published by the TCF. Are you referring to a use of modified Stack descriptions? Even then, the Policies require that the Publisher has registered and is operating a private-use CMP. That doesn't sound like your situation, but I may have misunderstood.  Here is the section to which I refer: https://iabeurope.eu/iab-europe-transparency-consent-framework-policies/#23_Managing_Purposes_and_Legal_Bases.

>Since this commit, we have had 404 results occurring when cloning the GVL with a language which is not the default one (EN).

If you can document this regression (failing URL(s), &c.) then someone can investigate.

>For now we made a workaround by hosting the translation files provided by the IAB here to our CDN, but of course this implies extra cost for us to deliver unused files instead of having a 404.

Some time back the TCF required CMPs to host/cache all GVL content, including translations, on their own CDNs. So this should be standard practise as I understand it. 

cc: @anderagakura

**Comment by Barben360** [comment]
Thanks for you answer.

Actually you are right, we are not translating ourselves any purpose or stack, but we are serving them while sending our notice as a response to a GET call triggerred by `__tcfapi('init', ...)` call. Therefore by serving the files as they are also through the CDN we actually have the translation retrieved twice. What we would like is to have the choice to serve them or not through a CDN or our API call to avoid doubling the costs.

**Comment by Barben360** [comment]
Hello, any update on the request?

**Comment by shortaflip** [comment]
Hi Barben,

404 from cloning the GVL is due to it attempting to retrieve language translations from your CMP's host.  In general, it shouldn't have to ping for language translations that its cache should already possess when you first made the GVL and called `gvl.changeLanguage('whatever language')`.

Can you post how you are creating, changing the language, and cloning the GVL?

**Comment by Barben360** [comment]
The problem is actually that we are using our own calls to serve the translations, with the rest of our notice texts and customizations, and therefore we don't need to rely on this internal system to get the texts we need. What happens now is that we are serving your translations files on our CDN to prevent errors in the console but we are not using them because our system was not built like that, and it's costly. All we need is just to have a parameter on your lib to disable the internal translations fetch system.

Moreover the [Belgian DPA decision](https://iabeurope.eu/all-news/belgian-dpa-decision-of-2nd-february-are-other-dpas-right-to-warn-about-continued-use-of-the-tcf/) will allow to modify some texts for European compliance, so the texts will soon need to be dynamic and then forcing to force static files will go against that.

**Comment by Barben360** [comment]
Hello, any update on this issue? We are still making useless calls as we are serving the data in a previous call.
