### ISSUE TITLE
ESM module output

### ISSUE THREAD

**Issue by perry-mitchell** [InteractiveAdvertisingBureau/iabtcf-es#323]
This library is extremely comprehensive, and would benefit its downstream use if it were outputting ESM modules, to improve dead code removal / tree-shaking.

It's already using typescript, and therefore has a build phase - why not convert it to ESM? ESM modules are already supported on newer NodeJS versions, and seem to be the direction the entire community is heading.

**Comment by Marco-Prontera** [comment]
Hi @shortaflip,
I saw this problem open and tried to get the desired result, as I also care that it is in ESM.
I opened a PR to be able to obtain ES Modules. (https://github.com/InteractiveAdvertisingBureau/iabtcf-es/pull/339)
I wanted to tell you that before checking that PR you should see the PR (https://github.com/InteractiveAdvertisingBureau/iabtcf-es/pull/338) as to get the result you had to update a few things in the project first. I took the opportunity to carry over some addictions.

Let me know ;)
