### ISSUE TITLE
Legitimate interest is set to true even with negative consent

### ISSUE THREAD

**Issue by yurigodke** [InteractiveAdvertisingBureau/iabtcf-es#330]
**Version**
1.4.0

**Module**
core - vendorlist

**Describe with reproduction steps – What is the expected behavior?**
The vendors with ids, 56, 415, 772, 883, 892, 945, 950, 953, 956, 1044 and 1065 the legitimate interest is set to true even with negative consent.

These vendors there aren't purposes and legIntPurposes set, I don't know if this is the reason, but only this vendors have this characteristics

**Comment by anderagakura** [comment]
@yurigodke You've highlighted vendors that only use `specialPurposes` and/or `features` and/or `specialFeatures`. To have the legitimate interest set to 0, the user have to exercise their “Right To Object”. Thus, from the moment that they are disclosed, then their bit is set to 1. There is no issue here

```
56, 883 = "purposes":[],"legIntPurposes":[],"flexiblePurposes":[],"specialPurposes":[1,2],"features":[],"specialFeatures":[]
772, 956, 1044 = "purposes":[],"legIntPurposes":[],"flexiblePurposes":[],"specialPurposes":[1],"features":[],"specialFeatures":[]
415, 950, 953 = "purposes":[],"legIntPurposes":[],"flexiblePurposes":[],"specialPurposes":[2],"features":[],"specialFeatures":[]
892 = "purposes":[],"legIntPurposes":[],"flexiblePurposes":[],"specialPurposes":[1],"features":[],"specialFeatures":[1]
1065 = "purposes":[],"legIntPurposes":[],"flexiblePurposes":[],"specialPurposes":[1],"features":[1],"specialFeatures":[1]
945 = "purposes":[],"legIntPurposes":[],"flexiblePurposes":[],"specialPurposes":[2],"features":[3],"specialFeatures":[]
```

**Comment by anderagakura** [comment]
@yurigodke You've highlighted vendors that only use `specialPurposes` and no other Purposes. From the moment that they are disclosed, then the bit must be set to 1. There is no issue here.
