### ISSUE TITLE
Complete the ESM and CJS build flow

### ISSUE THREAD

**Issue by Marco-Prontera** [InteractiveAdvertisingBureau/iabtcf-es#354]
_"Back to the Future"_
**This issue is a continuation of the main feature of ESM support for library modules.**

I am making the necessary changes, to make the library generate in a valid way both in CJS and in ESM.
It's a matter of days to get the job done.
Locally I have the changes ready to solve some problems encountered through the use of the next version 1.5.0-0.

I am doing some manual tests to verify the compatibility of the library to be compiled through the most famous build systems.
Here is a list of some "bundlers" I tried (and the problems I encounter I fix them):

- [x] Webpack 4
- [x] Webpack 5
- [x] Gulp (latest)
- [x] Vite (latest)
- [x] Rollup (latest)

All tests are done with clean configurations, to make sure that both using the library in CJS and ESM, no extra configuration is needed.
I will run other tests using also different node versions, I will stick to the maintenance releases here https://nodejs.org/en/about/releases/

- [x] nodejs 12
- [x] nodejs 14
- [x] nodejs 16

A problem that I encountered and that I fixed locally is the path of the files for ESM which must contain the suffix '.js' I add here a link to a giant typescript issue:https://github.com/microsoft/TypeScript/issues/16577#issuecomment-754941937
Typescript developers strongly recommend adding the '.js' extension manually to generate code that can be used properly as ESM. (This has no negative effect on the CJS version).

The CJS version is the one that is currently used by those who use this library, as well as myself. But the ESM version will give us many opportunities and also the whole JavaScript community is moving towards ESM by abandoning CJS.

I will also write a document explaining how to contribute to the project, as no CONTRIBUTION.md has been created.

I hope you enjoy 😜
@shortaflip 

_I created this issue because I will attach the respective PR to it and also to inform you of the progress_

**Comment by Marco-Prontera** [comment]
@shortaflip 
I add that I have tested the output in both ESM and CJS of the CMP with the chrome CMP Validator plugin of the IAB.

**Comment by shortaflip** [comment]
@Marco-Prontera, I have informed the IAB of pre-release v.1.5.0-3.
