### ISSUE TITLE
Fix for some bundlers

### ISSUE THREAD

**Issue by Marco-Prontera** [InteractiveAdvertisingBureau/iabtcf-es#357]
Hi, @shortaflip  here I am with the latest fix to add before releasing a version. 
This is a small change, and a slight improvement in performance, but a minor one.

I add the PR and we should be ready for the release

**Comment by shortaflip** [comment]
@Marco-Prontera, pre-release v1.5.0-3 is live using the tag `next`.  Let me know if you have anymore testing to be done, otherwise I will contact the IAB so that they can get other CMPs to try out this pre-release.

**Comment by Marco-Prontera** [comment]
@shortaflip Thanks!! 
I have tried and it works. I think you can contact the IAB.

**Comment by shortaflip** [comment]
Hi @Marco-Prontera,

I haven't gotten any response against or for your changes from the IAB and the pre-release seems to have gotten downloaded a few times the past week or so.  I'll be transitioning your pre-release to release next Tuesday.

**Comment by Marco-Prontera** [comment]
Hi @shortaflip ,

Perfect, thank you very much!
