### ISSUE TITLE
getTCData callback doesn't update addtlConsent for prebid call in React

### ISSUE THREAD

**Issue by eldzis** [InteractiveAdvertisingBureau/iabtcf-es#363]
**Version**
1.4.0

**Module (core, cmpapi, cli, stub, or testing)**
CmpApi

**Describe with reproduction steps – What is the expected behavior?**
In React initialising CmpApi with getTCData callback doesn't update `addtlConsent` value for prebid's received response, it is always static. Callback calls using `__tcfapi('getTCData', 2, (tcData, success) => {...}` returns correct `addtlConsent` value but prebid call gets only the addtlConsent value that cmpApi was initialised with.

`addtlConsent` value prebid sees on cmp initialisation
![image](https://user-images.githubusercontent.com/65354776/178247411-7c6ff79e-a609-4484-bffa-b3749127dd2a.png)

`addtlConsent` value stays the same after consenting to everything for prebid
![image](https://user-images.githubusercontent.com/65354776/178247781-2cc746b7-0813-4fe7-bad5-c89f059a4389.png)
Note that other fields are updated succesfully - tcString, eventStatus.

What console.logging `__tcfapi` callback returns after consenting:
![image](https://user-images.githubusercontent.com/65354776/178247988-6e116989-4901-4121-9297-19b919c4b31b.png)

How `cmpApi` is initialised in react: 
```javascript
useEffect(() => {
        if (addtlConsent) {
            setCmpApi(
                new CmpApi(2, 1, true, {
                    getTCData: (next, tcData, status) => {
                        /* If using with 'removeEventListener' command, add a check to see if tcData is not a boolean. */
                        if (typeof tcData !== "boolean") {
                            // tcData will be constructed via the TC string and can be added here
                            tcData.addtlConsent = addtlConsent;
                        }
                        // pass data and status along
                        next(tcData, status);
                    },
                })
            );
            setCmpApiInstance(true);
        }
    }, [addtlConsent]);
```

Note: `cmpApi` state in react is updated after `addtlConsent` state is updated. cmpApi state change does not have any impact on prebid's received `addtlConsent` response, it stays static all the time. `addtlConsent` state is updated before `cmpApi` state change, everything is fine in that part, thoroughly tested this part multiple times before opening an issue.

Is it possible that this can be React or prebid issue?

**Comment by PaulGrizzly** [comment]
getTCData middleware runs on every .update() call, but it always sets addtlConsent state value as it was at the time of CmpApi initialisation. To subscribe to the newest addtlConsent state in this middleware, useRef could be used like this:

   ```
const addtlConsentRef = useRef(addtlConsent);
   
   useEffect(() => {
        addtlConsentRef.current = addtlConsent;
        if (addtlConsent) {
            setCmpApi(
                new CmpApi(2, 1, true, {
                    getTCData: (next, tcData, status) => {
                        /* If using with 'removeEventListener' command, add a check to see if tcData is not a boolean. */
                        if (typeof tcData !== "boolean") {
                            // tcData will be constructed via the TC string and can be added here
                            tcData.addtlConsent = addtlConsent;
                        }
                        // pass data and status along
                        next(tcData, status);
                    },
                })
            );
            setCmpApiInstance(true);
        }
    }, [addtlConsent]);
addtlConsentRef.current = addtlConsent;
```
