### ISSUE TITLE
TCStringDecoder base64 encoding failed on android api level <=25 

### ISSUE THREAD

**Issue by af-jja** [InteractiveAdvertisingBureau/iabtcf-es#365]
**Version**
2.0.10

**Module (core, cmpapi, cli, stub, or testing)**
iabtcf-decoder

**Error**
`java.lang.NoClassDefFoundError: Failed resolution of: Ljava/util/Base64;
        at com.iabtcf.decoder.TCStringDecoder.vectorFromString(TCStringDecoder.java:37)
        at com.iabtcf.decoder.TCStringDecoder.decode(TCStringDecoder.java:57)
        at com.iabtcf.decoder.TCString.decode(TCString.java:43)`

**Describe with reproduction steps – What is the expected behavior?**
TCString decoding failed with an exception. 

On andorid api level 25 and below, `java.util.Base64` is not available. it should be replaced with `android.util.Base64`
see: https://stackoverflow.com/questions/48697766/android-studio-noclassdeffounderror-with-java-util-base64

is it possible to support an android/kotlin lib on maven as well?

**Comment by shortaflip** [comment]
@af-jja, you posted on the wrong library.  Closing this issue.
