### ISSUE TITLE
Ecma 5 not compliant build / default parameters (ES6) not transpiled

### ISSUE THREAD

**Issue by MFlyer** [InteractiveAdvertisingBureau/iabtcf-es#374]
**Version**: 1.5.3

**Module (core, cmpapi, cli, stub, or testing)**: Core

**Describe with reproduction steps – What is the expected behavior?**: Not ecma 5 compliant build

**Reference file/module**: https://github.com/InteractiveAdvertisingBureau/iabtcf-es/blob/master/modules/core/src/errors/TCModelError.ts

Although the terser option has ecma 5 target, both cjs and mjs builds have the default paramenter still available

**Comment by Marco-Prontera** [comment]
Hi @MFlyer I can fix this for `cjs`. 
For `mjs` it's right to use the default parameter, so we need to leave that.

**Comment by MFlyer** [comment]
Ciao! @Marco-Prontera, yep it's fine

Cheers
M.

**Comment by shortaflip** [comment]
@MFlyer and @Marco-Prontera v1.5.4-0 pre-release version of the library is live. This pre-release contains the bug fix for this issue. The `next` tag has been [published](https://www.npmjs.com/package/@iabtcf/core) and can be used to install this pre-release.

If neither of you find any issues from this pre-release then it will transition to a full release of v1.5.4 in about two weeks.
