### ISSUE TITLE
Global Privacy Platform (GPP) API Support

### ISSUE THREAD

**Issue by nejcsever** [InteractiveAdvertisingBureau/iabtcf-es#376]
**Global Privacy Platform (GPP) API Support**

I would like to know if there's a [Global Privacy Platform](https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform) (GPP) API specification support on your roadmap.

The specification for GPP API looks really similar to what's already implemented in cmp api but it should have exposed a different api calls and a bit different consent string.

I would just like to know if that's on your roadmap to include this support in the iabtcf-es or in any other repository?

Best,
Nejc

**Comment by shortaflip** [comment]
Hi @nejcsever,

So far I have not seen any calls for it or action plans. The global privacy working group has been solely focused on work directly related to GPP itself.

**Comment by nejcsever** [comment]
If anyone stumbles upon this issue, here's the **repository for GPP**:

**https://github.com/IABTechLab/iabgpp-es**
