### ISSUE TITLE
Core TC String: no default value bit in actual iab spec

### ISSUE THREAD

**Issue by a-s-rose** [InteractiveAdvertisingBureau/iabtcf-es#39]
Hi,

I'm a java backend developer working for a german company. We need to read values from tc-strings generated by this library. Therefore I found (maybe) an issue. I hope you could help me with.

So here is the case:
My frontend colleague has generated a tc-string for me with this library using the master branch. I tried to read it according to the iab spec [(IAB Transparency and Consent String with Global Vendor List Format)](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20Consent%20string%20and%20vendor%20list%20formats%20v2.md#the-core-string). My code failed to parse the tc-string, so I decoded it manually and interpreted the bits according to spec. The bits were somewhat weird after "IsRangeEncoding" part (I got vendor id's above 32000). 
So we did our test vice versa. I generated a tc-string and gave it to my frontend colleague to parse it with this library. This test also failed, so we compared the two implementations (Java/Javascript).

We found in [iabtcf/modules/core/src/encoder/field/VendorVectorEncoder.ts](https://github.com/chrispaterson/iabtcf/blob/master/modules/core/src/encoder/field/VendorVectorEncoder.ts) at line 92 that 1 bit for a default value is read (after reading the "IsRangeEncoding" part). In the iab spec there is no default value to set or read after "IsRangeEncoding" - so my java code hasn't read this 1 bit value and the parsed values were wrong. 

Could you please check if reading or setting the default value is wrong or if the spec lacks this value?

Many thanks in advance,
Antje Rose

**Comment by chrispaterson** [comment]
Ah, thank you!  I wrote that part of the code when the default value was still a part of the spec.  We realized that there is never a reason to set the default value to `1` and have an inverted `set` of IDs.  I'll make a fix for the beta.1 version of the library.

**Comment by a-s-rose** [comment]
Great, thank you!

**Comment by chrispaterson** [comment]
I made the change here: https://github.com/chrispaterson/iabtcf/commit/e6854c7f6dba6008a9f2dc1faae7006449e34f67#diff-92733b14f7144bf660c31d9f7e30de57

**Comment by iewrer** [comment]
Hi,
Sorry to bother, but when will this fix be released?

**Comment by wittjill** [comment]
was released last week.
