### ISSUE TITLE
Help you through the complete release of TCF v2.2

### ISSUE THREAD

**Issue by marco-prontera** [InteractiveAdvertisingBureau/iabtcf-es#411]
Hello @aitnitishshelage, given the need to have the TCF v2.2 and the library that works correctly, I'm writing here what should be done in sequence. Just to help you since this help us to get everything ready and enable us to upgrade our CMPs with the new TCF v2.2

1) Merge of #389 (required for IL TCF v2.2 in order for the new parameters to be used as indicated by the IAB)
2) Merge of #403 (required to make sure that the tests all run correctly and to be calm in doing the review)
3) Merge of #404 (required because for pt, sr languages we can't use the files that IAB release, see issue related)
4) Merge of #407 (required because almost all CMP uses restrictions and without this fix we can't use restrictions for performance reasons)
5) Merge of #410 (required for TCF v2.2 in order to match all requirements)
6) Merge of #409 (required (or maybe optional) to be sure that every release published on NPM is done with yarn postversion, of course develop must be rebased into master)

then release v2.0.0

**Comment by marco-prontera** [comment]
Hi @iabmayank, I see you are assigned to this, can you help us please?

**Comment by iabmayank** [comment]
@marco-prontera please can you open and share the PR and let us know the order in which it's needs to be merged for the release. we will follow the same.

**Comment by lamrowena** [comment]
@marco-prontera - this is in progress and will be released soon.

**Comment by marco-prontera** [comment]
> @marco-prontera - this is in progress and will be released soon.

Of course, I opened some PR to finish and get the release ready to let CMPs update their implementation to switch from TCF v2.0 to v2.2.
I also opened an issue and a PR to enable the AMP project fix their implementation to support also the TCF policy version 4.
I also tested the PR (those described in this issue) merged in my own package to implement the CMP and it's successfully validated through the validator extension (https://chrome.google.com/webstore/detail/cmp-validator/ffhhjklgcfabkpholngojpkijlafjooc).
Maybe I'm missing something, maybe there are other reasons I don't know?

**Comment by mguerra10128** [comment]
Is there a estimate of when these merged changed will get released?

**Comment by mguerra10128** [comment]
just following up here as we are aiming to go live on 2.2 early next week, and require the library changes to be released to complete end to end testing

**Comment by sinsimon** [comment]
Hello @iabmayank @sevriugin and @lamrowena, we need to plan our CMP TCF 2.2 update as well. Can you give us an estimate on when the merged changed will a release? Thanks

**Comment by eldzis** [comment]
Hi everyone! We are also waiting for essential tools TCF v2.2 update. Would be great if you could give us any ETA

**Comment by marco-prontera** [comment]
This issue can be closed. Every changes is published in the new npm package scope `@iabtechlabtcf` , the code to support the new TCF version is published under 1.5.9 version.
https://www.npmjs.com/search?q=%40iabtechlabtcf
