### ISSUE TITLE
Implement support for GVL v3

### ISSUE THREAD

**Issue by nejcsever** [InteractiveAdvertisingBureau/iabtcf-es#416]
There's a deadline for CMPs to support TCF v2.2 by the end of September and this official library is still not supporting one of the core features of this update.

Please add support for GVL v3.

**Comment by sevriugin** [comment]
Have you manage to check the lates version - [1.5.9](https://www.npmjs.com/package/@iabtechlabtcf/core) lmk if you have any issue with this one, cheers

**Comment by nejcsever** [comment]
I didn't know that the scope of the packages changed from @iabtcf to @iabtechlabtcf so I was depending on @iabtcf/core instead of @iabtechlabtcf/core. Also the version of latest release for this repository is set to 1.5.6 so I thought this was the latest one.

@sevriugin Thank you for pointing me in the right direction. @iabtechlabtcf/core indeed supports GVL v3 fields.
