### ISSUE TITLE
Don't have an option for features in consent string

### ISSUE THREAD

**Issue by rutujaN2** [InteractiveAdvertisingBureau/iabtcf-es#428]
In https://iabtcf.com/?#/encode, we can see there are options for purposes, special features, etc. but the same is not available for features.

Features refer to specific techniques or technologies that companies might use when processing personal data for one of the defined purposes.
There are 3 features:
1.Match and combine offline data sources
2.Link different devices
3.Receive and use automatically-sent device characteristics for identification

**Comment by janwinkler** [comment]
Features are a combination of data usages for which a vendor needs purposes. Hence there is no need for a signal.

**Comment by rutujaN2** [comment]
Ohh. Then if there is a scenario where I want to check if the consent string resembles that consent is given for all the 3 features, how can I check this?

**Comment by janwinkler** [comment]
You dont. You check if vendor and purpose/special purposes have consent. the vendor will need to decide which purposes/special purposes are contained in each feature they are using.

**Comment by HeinzBaumann** [comment]
Answered. Closing this issue.
