### ISSUE TITLE
IABTCF online decoder not recognizing new TCString

### ISSUE THREAD

**Issue by goncalosilva-appgeneration** [InteractiveAdvertisingBureau/iabtcf-es#429]
**Version**
1.0.0

**Module (core, cmpapi, cli, stub, or testing)**
core

**Describe with reproduction steps – What is the expected behavior?**
1. Open [iabtcf.com/#/decode](iabtcf.com/#/decode)
2. Entered the following Base64 string DP1BnkAP1BnkAEsACCENAaEgAAAAAEPgAB6YAAAQaQD2F2K2kKFkPCuQWYoQBCijaEAhQBAAAkCBIAAgAUgQAgFIIAgABFAAEAAAAAAQEgCQAAQABAAAIACgAAAAAAIAAAAAAAQQAAAAAIAAACAAAAEAQAAAAAQAAAAIAABEhCAAQQAMAAAAAAASAAAAAAAAAAABAAAAAAAAAAAAAAQAAAAAgAA.YAAADmAAAAA
3. Nothing shows up.

I got the string above after using Google UMP on Android, and reading the resulting TCString from local storage.
Strangely enough, if I change the first characters from DP1 to CP1, parsing occurs without issues.
Is this a new format?
I can't find information about it anywhere.

**Comment by sevriugin** [comment]
It looks like CPM has changed version format from 2 to 3 and this is the first character, that is why `C` became `D`. But I think the format for TCF v2.2 has not been changed, it still should be `2` and what is changing is policy version  to 4 see the doc [here](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20Consent%20string%20and%20vendor%20list%20formats%20v2.md#creating-a-tc-string)

**Comment by goncalosilva-appgeneration** [comment]
Exactly, I thought I was going insane here. All the sources I looked at didn't mention changes for the "core version" in TCF v2.2 (the C/D characters).

With the exception of the invalid "core version", the rest of the encoded information is consistent with selecting "Consent All" on the form.
It doesn't seem to be missing anything

I will close this bug report and reach out to the Google UMP team.
Thanks for the help!

**Comment by LagoonProject** [comment]
> * [iabtcf.com/#/decode](iabtcf.com/#/decode)

Hi @goncalosilva-appgeneration, I'm facing the same issue with tcString not being decoded. Do you have any feedback from Google UMP ? 
Thanks.

**Comment by martinpraznovskypp** [comment]
Hi @LagoonProject  and @goncalosilva-appgeneration  I have the similar issue with the new "D" character in tcf v2.2 with the google ump we use as well. 
Is there any progress on this?

**Comment by andwun** [comment]
Gonçalo has posted this issue on the Google AdMob Developer forum:
https://groups.google.com/g/google-admob-ads-sdk/c/BbrnlqAxev8

The thread only got a text block answer so far from the moderators.

I had just replied all there to clarify that this affects all platforms and all users of Google UMP and needs to be investigated and fixed ASAP, but my message has just got deleted.

**Comment by goncalosilva-appgeneration** [comment]
@martinpraznovskypp, just replace the lead letter from "D" to "C".

@LagoonProject I don't have feedback from Google yet.

Although the issue is very obvious, I sent them an Android Studio sample through the AdMob Developer form and described the issue in detail - it's not showing yet because it's pending approval.

But I'm starting to doubt they're going to fix this in a short amount of time. I'm not even sure their internal dev team knows about this.

**Comment by andwun** [comment]
I've got an email from AdMob support today, they're investigating the issue.

**Comment by StCyr** [comment]
oh god what a mess :-(

**Comment by nhc-motosumo** [comment]
> I've got a response to my support ticket from AdMob support today, they're investigating the issue.

Unfortunately they just bounced it as SEP: https://groups.google.com/g/google-admob-ads-sdk/c/BbrnlqAxev8/m/X6TcGdP3AQAJ

**Comment by andwun** [comment]
@nhc-motosumo Yeah, forget the developer forum.
I've found a way to open a real support ticket through the AdMob help center.
After that I got an email, that they're investigating it.
Received no further updates so far though.

**Comment by andwun** [comment]
AdMob support now says the issue has been fixed, the invalid consent strings should be automatically invalidated and the affected users will be prompted for consent again.
So far, I was able to confirm this on one of our sites.

**Comment by sevriugin** [comment]
Good news, thanks a lot, guys 🔥

**Comment by nhc-motosumo** [comment]
Awesome! Thanks for following up on this :pray:
