### ISSUE TITLE
TCF 2.2 Validator does not work with the lib for some reason

### ISSUE THREAD

**Issue by domonkosferenczy** [InteractiveAdvertisingBureau/iabtcf-es#430]
I'm using the latest modules from this repository (cmpApi, core, Stub) and using GVL V3 hosted on my own site.
Consent String is generated, __tcfapi retrieves the data for the addEventListener command.

**Problem:** I have installed the CMP Validator 2.2 (latest version as of today) and I don't see any information on the TCF 2.2 Validator. See image attached:
<img width="1342" alt="image" src="https://github.com/InteractiveAdvertisingBureau/iabtcf-es/assets/46500141/9e2bc480-adc2-446d-aef3-2cce895a428b">

I don't get any error messages from anything.

**Comment by HeinzBaumann** [comment]
@domonkosferenczy any chance you can give me access to your test page so we can debug this. Thanks!

**Comment by domonkosferenczy** [comment]
@HeinzBaumann found the issue. Issue: `cmpstub()` was called after the `cmpApi` was created. Thanks!
