### ISSUE TITLE
Vendors Count

### ISSUE THREAD

**Issue by littlenoah89** [InteractiveAdvertisingBureau/iabtcf-es#433]
**v1.5.9**

**Module (core, cmpapi, cli, stub, or testing)** CORE

Hi everyone,
I have noticed a discrepancy in values between the number of vendorIds and the number of vendors in the GVL. Specifically, version 27 of the vendor-list v3 has 765 vendorIds but 760 vendors. This affects the choice of the value to be used to display the vendors count. What should be the correct value to consider?

Anyone with the same problem?

**Comment by sevriugin** [comment]
There are deleted vendors with `deletedDate` and  the count for deleted vendors is 5, so the library returns correct number

**Comment by littlenoah89** [comment]
Okay, perfect. It all makes sense to me now.
Thank you for the prompt response.
