### ISSUE TITLE
 CMP API Not Detected During Chrome Extension Validation

### ISSUE THREAD

**Issue by naeem-epi** [InteractiveAdvertisingBureau/iabtcf-es#434]
**Version**
1.5.10
**Module (core, cmpapi, cli, stub, or testing)**
core,cmpapi
**Describe with reproduction steps – What is the expected behavior?**

I've integrated the Consent Management Platform (CMP) API into our website. However, when I attempt to validate it using Chrome extension tools, the validation suggests that the CMP API is not detected. Strangely, when I manually type the CMP API function (e.g., __tcfapi) in the console, it returns an object.

I want to note that I haven't registered a CMP ID; instead, I'm using a dummy CMP ID, which is 1003 for IAB submission. Despite this, I'm unable to identify where the issue lies. Any guidance on resolving this matter would be greatly appreciated.

<img width="947" alt="cmp-api-not-found" src="https://github.com/InteractiveAdvertisingBureau/iabtcf-es/assets/77724049/e0b34aaa-0811-4261-b72b-bed75269d3ae">

**Comment by HeinzBaumann** [comment]
@naeem-epi can you please grant me access to your test site so I can take a look. My guess is that there is no TCF API present and / or accessible outside the mainframe. You will need to set this up based on the TCF spec to make it work. I am happy to take a quick look at your test site.

**Comment by ANGIL21** [comment]
Ok. Perfecto

**Comment by naeem-epi** [comment]
> @naeem-epi can you please grant me access to your test site so I can take a look. My guess is that there is no TCF API present and / or accessible outside the mainframe. You will need to set this up based on the TCF spec to make it work. I am happy to take a quick look at your test site.

The password is `**skotho**`
Please note that the banner is exclusively accessible in the EU region. Kindly ensure that you are browsing from within the EU region. If you are located outside the EU, feel free to use a VPN to access the site. Thank you!

**Comment by HeinzBaumann** [comment]
@naeem-epi I quickly checked. It looks to me as there is no __tcfapi on this page, hence you get the error message in the TCF validator. 
The location cookie you set shows location Frankfurt/Germany. My browser is EU. I only see a regular cookie banner, not a CMP. 
Hope this helps
