### ISSUE TITLE
Typo among the texts of purposes-it.json

### ISSUE THREAD

**Issue by littlenoah89** [InteractiveAdvertisingBureau/iabtcf-es#451]
**Module**
Core

**Describe with reproduction steps – What is the expected behavior?**
We have found a typo among the texts translated into Italian in the file purposes-it.json.
Specifically, the title of specialPurposes number 2 is not "Erogare e presentare pubblicità e contenutio" but "Erogare e presentare pubblicità e contenuto".
We kindly ask if it is possible to resolve this.

Thank you.

**Comment by HeinzBaumann** [comment]
I sent it to the people at IAB EU to get it fixed.

**Comment by HeinzBaumann** [comment]
I fixed it. Should role out by the next update.
