### ISSUE TITLE
ES6 code in compiled package

### ISSUE THREAD

**Issue by saraneus** [InteractiveAdvertisingBureau/iabtcf-es#46]
I have a Webpack project set up and when I import the CmpApi from node_modules babel throws errors on spread operators. As far as I know projects should exclude /node_modules/ from compiling with babel so external modules are required to be already compiled to ES2015.

`ERROR in ./node_modules/@iabtcf/cmpapi/lib/command/responsebuilders/ResponseBuilder.js
Module parse failed: Unexpected token (5:17)
You may need an appropriate loader to handle this file type.
| class ResponseBuilder {
|     buildResponse() {
|         return { ...this };
|     }
| }
 @ ./node_modules/@iabtcf/cmpapi/lib/command/responsebuilders/TCDataBldr.js 5:26-54
 @ ./node_modules/@iabtcf/cmpapi/lib/command/responsebuilders/index.js
 @ ./node_modules/@iabtcf/cmpapi/lib/command/commands/GetInAppTcDataCommand.js
 @ ./node_modules/@iabtcf/cmpapi/lib/command/commands/index.js
 @ ./node_modules/@iabtcf/cmpapi/lib/command/CommandStream.js
 @ ./node_modules/@iabtcf/cmpapi/lib/command/index.js
 @ ./node_modules/@iabtcf/cmpapi/lib/CmpApi.js
 @ ./node_modules/@iabtcf/cmpapi/lib/index.js
 @ ./src/cmp/Cmp.jsx
 @ ./src/cmp/index.js
 @ multi (webpack)-dev-server/client?http://localhost:5003 webpack/hot/dev-server ./cmp/index.js`

.babelrc:
`{
    "sourceMaps": true,
    "presets": [
        [
            "es2015",
            {
                "loose": true
            }
        ],
        "stage-0"
    ],
    "plugins": [
        [
            "transform-decorators-legacy"
        ],
        [
            "transform-react-jsx",
            {
                "pragma": "h"
            }
        ],
        [
            "transform-object-assign"
        ],
        "transform-object-rest-spread",
        [
            "transform-runtime",
            {
                "regenerator": true,
                "polyfill": true,
                "helpers": true
            }
        ]
    ]
}
`

webpack.config.babel.js:
`...
{
                test: /\.jsx?$/,
                exclude: /node_modules/,
                use: 'babel-loader'
            },
...`

**Comment by chrispaterson** [comment]
I recompiled in beta.3 let me know if that works
