### ISSUE TITLE
JSON-Fetcher throws Error in IE11

### ISSUE THREAD

**Issue by saraneus** [InteractiveAdvertisingBureau/iabtcf-es#47]
When the GVL is loaded in IE11, the line
`req.responseType = 'json';` in core/lib/Json.js
throws an InvalidStateError in IE11.

According to stackoverflow if you put that line after calling .open() it will work in IE11, but will throw errors in Edge: https://stackoverflow.com/questions/20760635/why-does-setting-xmlhttprequest-responsetype-before-calling-open-throw/34647690

The same problem exists with the **withCredentials** parameter.

**Comment by chrispaterson** [comment]
Please verify that beta.3 fixes this – I don't have a way to test it right now
