### ISSUE TITLE
what is Overflow object in https://vendorlist.consensu.org/v2/vendor-list.json

### ISSUE THREAD

**Issue by chandanamuppalla** [InteractiveAdvertisingBureau/iabtcf-es#49]
I see an object of   below type
"overflow": {
        "httpGetLimit": 128
      }

what excatly it does

**Comment by chrispaterson** [comment]
https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20Consent%20string%20and%20vendor%20list%20formats%20v2.md#what-is-contained-in-the-global-vendor-list

**Comment by chrispaterson** [comment]
Listed as the last bullet
