### ISSUE TITLE
No BitLength Definition of publisherConsents

### ISSUE THREAD

**Issue by demi-fw** [InteractiveAdvertisingBureau/iabtcf-es#52]
When encoding and decoding the Publisher TC Section,  we found there is no Bitlength definition of `publisherConsents` field.

It seems that this issue is related to the incorrect fix of issue:  https://github.com/InteractiveAdvertisingBureau/iabtcf-es/issues/45

https://github.com/InteractiveAdvertisingBureau/iabtcf-es/blob/87156f8f34a90b8e77698b0b578f8275e4f8ebdb/modules/core/src/encoder/BitLength.ts#L13-L15
The line defining Bitlength of `publisherConsents` is missing.

**Comment by chrispaterson** [comment]
This is release in beta.4
