### ISSUE TITLE
Unable to set consentlanguage and missing symbol polyfill in IE

### ISSUE THREAD

**Issue by mghouse036** [InteractiveAdvertisingBureau/iabtcf-es#56]
Facing below issues on IE11
1. When I try set the default consent language 'EN', I am getting unhandled promise rejection error. 
2. Symbol, Number.isInteger polyfill are not added for IE.
3. I see below Circular dependencies error call stack:
`Circular dependency: node_modules\@iabtcf\core\lib\encoder\index.js -> node_modules\@iabtcf\core\lib\encoder\field\index.js -> node_modules\@iabtcf\core\lib\encoder\field\FieldEncoderMap.js -> node_modules\@iabtcf\core\lib\encoder\field\VendorVectorEncoder.js -> node_modules\@iabtcf\core\lib\encoder\index.js
Circular dependency: node_modules\@iabtcf\core\lib\encoder\index.js -> node_modules\@iabtcf\core\lib\encoder\field\index.js -> node_modules\@iabtcf\core\lib\encoder\field\FieldEncoderMap.js -> node_modules\@iabtcf\core\lib\encoder\field\VendorVectorEncoder.js ->  
commonjs-proxy:d:\workspace\banner-script\node_modules\@iabtcf\core\lib\encoder\index.js -> node_modules\@iabtcf\core\lib\encoder\index.js`

**Comment by chrispaterson** [comment]
Can you tell me which version you’re using?

**Comment by mghouse036** [comment]
It's latest version 1.0.0-beta.5

**Comment by sunandhaC** [comment]
@chrispaterson Can we please publish the library to get this fixes available for us.

**Comment by chrispaterson** [comment]
I will publish on Thursday.

**Comment by chrispaterson** [comment]
https://github.com/InteractiveAdvertisingBureau/iabtcf-es/projects/7

**Comment by mghouse036** [comment]
@chrispaterson, Found one more issue consentLanguage is not getting initialised in IE. It's empty set when I set the language

**Comment by chrispaterson** [comment]
@mghouse036 can you open a separate issue for that?  https://github.com/InteractiveAdvertisingBureau/iabtcf-es/issues/new 
I'm not sure I fully understand how to reproduce maybe you can describe it there a little more?  Thanks!
