### ISSUE TITLE
Can not set vendorListVersion on TCModel when GVL is loaded from JSON Object

### ISSUE THREAD

**Issue by kirly-af** [InteractiveAdvertisingBureau/iabtcf-es#60]
At the moment, the only way to set the vendorListVersion property is to set it before the gvl property.
```js
import { TCString, TCModel, GVL } from '@iabtcf/core';

const gvl = new GVL(vendorListObject);
const tcModel = new TCModel(gvl); // should not need to wait for readyPromise
tcModel.vendorListVersion = 42; // will not work
TCString.encode(tcModel); // throws TCModelError: invalid value 0 passed for vendorListVersion
```

My workaround:
```js
import { TCString, TCModel, GVL } from '@iabtcf/core';

const gvl = new GVL(vendorListObject);
const tcModel = new TCModel();
tcModel.vendorListVersion = 42;
tcModel.gvl = gvl;
TCString.encode(tcModel);
```

I identified 2 problems:
* a dependency on readyPromise in `set gvl()` => https://github.com/InteractiveAdvertisingBureau/iabtcf-es/blob/master/modules/core/src/TCModel.ts#L161
* we can not set the vendorListVersion if it the same as the one in the vendorList object: https://github.com/InteractiveAdvertisingBureau/iabtcf-es/blob/master/modules/core/src/TCModel.ts#L331

This could be fixed by adding a `if (gvl.readyPromise === undefined) {}` in `set gvl()`. For example:

```js
class TCModel {
    public set gvl(gvl: GVL) {

        /**
         * Set the reference but wait to see the other values for when the data populates
         */
        this.gvl_ = gvl;
        this.publisherRestrictions.gvl = gvl;
    
        if (gvl.readyPromise === undefined) {
            this.vendorListVersion_ = gvl.vendorListVersion;
            this.policyVersion_ = gvl.tcfPolicyVersion;
            this.consentLanguage_ = gvl.language;  
        } else {
            gvl.readyPromise.then((): void => {
    
                this.vendorListVersion_ = gvl.vendorListVersion;
                this.policyVersion_ = gvl.tcfPolicyVersion;
                this.consentLanguage_ = gvl.language;
          
            });
      
        }
    }
}
```

**Comment by kirly-af** [comment]
Actually I realized that readyPromise is always set because of the type conversion of the object in GVL.

**Comment by kirly-af** [comment]
I guess a isReady flag could be set, avoiding to rely on readyPromise if not necessary.

**Comment by chrispaterson** [comment]
Hi @kirly-af the `vendorListVersion` is set from the vendorList object passed in if one is passed in.  So, there's no reason to set it after the fact.  I don't think an `isReady` flag is necessary because you can use the promise at any time.  If it is already resolved then it will just execute immediately.

**Comment by kirly-af** [comment]
Hi @chrispaterson,

The vendorListVersion is set in the readyPromise.then() callback, which means it is not synchronous as it will be executed in a different tick. When setting the GVL from an Object, this should not be necessary (as stated in the docs).

**Comment by kirly-af** [comment]
A small example to illustrate what I say:

```js
const a = Promise.resolve();                                                                                         
                                                                                                                     
a.then(() => console.log('123')); // the then callback will be executed on a next tick                                                                                    
console.log('567');
```

const a = Promise.resolve();                                                                                         
                                                                                                                     
a.then(() => console.log('123'));                                                                                    
console.log('567');  
```

The output will be:
567
123

**Comment by chrispaterson** [comment]
Here's my concern with implementing your suggestion:

> I guess a isReady flag could be set, avoiding to rely on readyPromise if not necessary.

Doing this creates an unreliable interface for knowing when the GVL is ready to be used.  Because any downstream user of the GVL object should not have to know how it was created but only that when the readyPromise resolves it is populated.  I don't see a big need to have a synchronous vendor list version property set because it should only be used on encode.  If you really want to get the vendor list version synchronously after setting it you can get it by accessing `tcModel.gvl.vendorListVersion`

**Comment by chrispaterson** [comment]
Ok I see, I'll add a sychronous `isReady` flag.
