### ISSUE TITLE
Legitimate Interest for Special Purpose

### ISSUE THREAD

**Issue by saraneus** [InteractiveAdvertisingBureau/iabtcf-es#63]
Where is the consent for Special Purposes stored in the TCModel? I can only find properties for Purpose Consent and LegInt Purposes, but not for Special Purposes.

I might be missunderstanding the concept of Special Purposes. Appreciate any hint.

**Comment by nejcsever** [comment]
Special Purposes do not require consent, they just need to bi disclosed to the user in the UI if at least one of the disclosed Vendors declares using them. Same goes for **features**.

Here are two examples that may clarify those things:

**First Example (no special purposes):**
You're only disclosing Vendors who's `specialPurposes` array is empty ([]) in the GVL, then you don't even need to show special purposes on the UI.

**Second Example (vendors with special purposes):**
Let's say that you're disclosing one vendor that has `specialPurposes` set to [1], then you need to show special purpose 1 to the user in the UI. That's all that needs to be done in that case, you don't need the actual consent for special purposes.

That's at least my understanding of it, hope it helps. :)

**Comment by saraneus** [comment]
@nejcsever 
Many thanks to your reply. I think the TCF presentation confused me, because it says that Special Purposes are based on Legitimate Interest - same as some of the Purposes, they may be opt-out by the user.
![image](https://user-images.githubusercontent.com/39457035/73728294-0ab79700-476e-11ea-8e8c-bf63f58eef74.png)
while Features says "disclosure only", which makes it very clear to me.
![image](https://user-images.githubusercontent.com/39457035/73728319-199e4980-476e-11ea-92a0-99365ef9af36.png)

**Comment by nejcsever** [comment]
No problem.

To clarify things further you can also check the official [Policies PDF](https://iabeurope.eu/tcfdocuments/documents/legal/tcfpolicyFINALv2.pdf). 13th point on page 6 defines special purpose:

> 13. “**Special Purpose**” means one of the defined purposes for processing of data, including
> users’ personal data, by participants in the Framework that are defined in the Policies or the
> Specifications for which Vendors declare a Legal Basis in the GVL and for which the user is not
> given choice by a CMP.

To point out the important thing: 

> for which the user is not given choice by a CMP

**Comment by chrispaterson** [comment]
Thanks for answering this @nejcsever , that is right.  Special Purposes are pure disclosure with no ability for a user to opt in/out or accept/reject.
