### ISSUE TITLE
Symbol polyfill is not added properly in IE 11 in cmpapi(beta.6)

### ISSUE THREAD

**Issue by mghouse036** [InteractiveAdvertisingBureau/iabtcf-es#66]
**Without including as package dependencies("es6-symbol": "3.1.3")**
Seeing Symbol in not undefined in IE, When I try include cmpapi(beta.6).
![image](https://user-images.githubusercontent.com/26306579/73817418-da750480-4810-11ea-8828-b85ec9f896df.png)

**Including as package dependencies("es6-symbol": "3.1.3")**
After importing the symbol for IE, Seeing consent language is not initialized error when I set default 'EN' value
![image](https://user-images.githubusercontent.com/26306579/73817736-b5cd5c80-4811-11ea-9e51-60cc1064436f.png)

**Comment by chrispaterson** [comment]
I'm adding the "ES2015.Symbol" lib to the tsconfig.js.  But I'm not sure there's enough to go on for the second issue with the setting of consent language.  Once beta.7 is released (today) can you please try again and open another issue if the consent language problem still persists?
