### ISSUE TITLE
getTCData result in null TCData if GDPRApplies is false

### ISSUE THREAD

**Issue by DianeJane** [InteractiveAdvertisingBureau/iabtcf-es#67]
Hi I'm using CmpApi tool. I've followed the following instructions when GDPRApplies is false:
[@iabtcf/cmpapi](https://github.com/InteractiveAdvertisingBureau/iabtcf-es/tree/master/modules/cmpapi#gdpr-doesnt-apply)

> In the case that GDPR does not apply, simply set the TCModel to null. That's all.

When I'm calling getTCData it returns TCData: null and success: false.

But in the documentation it says:
[getTCData](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20CMP%20API%20v2.md#gettcdata)

>  If GDPR does not apply to this user in this context (gdprApplies=false) then this user will have no Transparency and Consent values and a TCData object with no Transparency and Consent values for any Vendors will be passed to the callback function.

[TCData](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20CMP%20API%20v2.md#tcdata)

>  If GDPR does not apply to this user in this context then only gdprApplies, tcfPolicyVersion, cmpId and cmpVersion shall exist in the object.

How would I go about returning only gdprApplies, tcfPolicyVersion, cmpId and cmpVersion values instead of null for this use-case?

**Comment by chrispaterson** [comment]
Diane, I think this is an implementation mistake.  I'll try to get a fix into the release that will go out next week on the 13th.
