### ISSUE TITLE
GVLError launching TCF2.0 string encoding js library

### ISSUE THREAD

**Issue by zezzibenji** [InteractiveAdvertisingBureau/iabtcf-es#68]
Dears,
we are getting some troubles using the js library for managing the TCF string 2.0.
We installed it straightforward using the suggested npm command:
`npm install @iabtcf/core --save` 
Then we have included the js script in a page following the provided example:

	import {TCModel, TCString, GVL} from '@iabtcf/core';
	
	 
	
	/**
	
	 *  the IAB requires CMPs to host their own vendor-list.json files.  This must
	
	 *  be set before creating any instance of the GVL class.
	
	 */
	
	GVL.baseURL = "./resources/vendor-list.json";
	
	 
	
	// create a new TC string
	
	const tcModel = new TCModel(new GVL());
	
	 
	
	// Some fields will not be populated until a GVL is loaded
	
	tcModel.gvl.readPromise.then(() => {
	
	 
	
	  // Set values on tcModel...
	
	 
	
	  const encodedString = TCString.encode(tcModel);
	
	 
	
	  console.log(encodedString); // TC string encoded begins with 'C'
	
	 
	
	})
	
	// take an encoded TC string and decode into a TCModel
	
	//const decodedTCModel = TCString.decode(encodedString);

but when we open the page with the embedded js we get the following error:

	GVLError.ts:16 Uncaught GVLError: must specify GVL.baseUrl before loading GVL json
	
	    at new t (http://localhost:1234/iabapi2test.e31bb0bc.js:130:481)
	
	    at new t (http://localhost:1234/iabapi2test.e31bb0bc.js:226:736)
	
	    at Object.parcelRequire.index.js.@iabtcf/core (http://localhost:1234/iabapi2test.e31bb0bc.js:248:33)
	
	    at newRequire (http://localhost:1234/iabapi2test.e31bb0bc.js:47:24)
	
	    at http://localhost:1234/iabapi2test.e31bb0bc.js:81:7
	
	    at http://localhost:1234/iabapi2test.e31bb0bc.js:120:3
	
	t @ GVLError.ts:16
	
	t @ GVL.ts:248
	
	parcelRequire.index.js.@iabtcf/core @ index.js:11
	
	newRequire @ iabapi2test.e31bb0bc.js:47
	
	(anonymous) @ iabapi2test.e31bb0bc.js:81
	
	(anonymous) @ iabapi2test.e31bb0bc.js:120

We tried to change the value of GVL.baseURL to https://vendorlist.consensu.org/v2/vendor-list.json but the result was the same.

Do you have any suggestion for us? 

Thanks for your kind support,
Luigi

**Comment by DianeJane** [comment]
I ran into the same problem, when you try using the vendorlist from consensu.org it causes this error:
> Uncaught GVLError: Invalid baseUrl!  You may not pull directly from vendorlist.consensu.org and must provide your own cache

Try hosting the vendor list somewhere and using that URL.

Also `readPromise` should be `readyPromise`.

**Comment by zezzibenji** [comment]
Thanks @DianeJane , it works!
