### ISSUE TITLE
getTCData TCData object does not have cmpStatus

### ISSUE THREAD

**Issue by DianeJane** [InteractiveAdvertisingBureau/iabtcf-es#71]
**Version**
^1.0.0-beta.7

**Module**
cmpapi

**Describe the bug**
`TCData` object from `getTCData` call does not return `cmpStatus`
<img width="676" alt="Screen Shot 2020-02-07 at 11 52 51 AM" src="https://user-images.githubusercontent.com/6456249/74000061-b694f880-49a1-11ea-929b-64cea7f7c33f.png">

From [TCData](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20CMP%20API%20v2.md#tcdata)
```
TCData = {
  tcString: 'base64url-encoded TC string with segments',
  tcfPolicyVersion: 2,
  cmpId:1000,
  cmpVersion: 1000,
  .......
  /**
   * see Ping Status Codes in following table
   */
  cmpStatus: 'string',

```

**Steps to Reproduce**
1.  Create tcModel and assign to CmpApi.
```
const decodedTCModel = TCString.decode(data.cookie);
cmpApi.tcModel = decodedTCModel;
```
 
2. Call  `getTCData` and check tcData object.
```
__tcfapi('getTCData', 2, (tcData, success) =>  {
    if (success) {
        console.log(`success: ${success}`);
        console.log({tcData});window.tcData = tcData;
    }else {
        console.log(`success: ${success}`);
    }
})
```

**Expected behavior**
`tcData` should have cmpStatus.

**Actual behavior**
`tcData` does not have cmpStatus.

**Comment by chrispaterson** [comment]
Good catch, this was added to the spec in December and I haven't incorporated it just yet.
https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/commit/6fde6adcb4d583d96c20db66303a7884bf1b15d7#diff-e3f0c1cbbc55186284969bbd4784fa52
