### ISSUE TITLE
TCString from getTCData does not match TCString used to decode TCModel

### ISSUE THREAD

**Issue by DianeJane** [InteractiveAdvertisingBureau/iabtcf-es#72]
**Version**
1.0.0-beta.7

**Module**
cmpapi

**Describe the bug**
`TCString` from getTCData's `TCData` does not match `TCString` used to decode `TCModel`

**Steps to Reproduce**

1. Create `TCModel` from cookie using `TCString.decode`
2. Assign `TCModel` object to `CmpApi.tcModel`
code used here:
```
const decodedTCModel = TCString.decode(data.cookie);
cmpApi.tcModel = decodedTCModel;
__tcfapi('getTCData', 2, (tcData, success) =>  {
    if (success) {
        console.log(`From cookie: ${data.cookie}`);
        console.log(`From TCData: ${tcData.tcString}`);
        console.log(`isEqual${tcData.tcString == data.cookie}`);
        console.log({tcData});
        window.tcData = tcData;
    }
});
```
**Expected behavior**
`TCData.tcString` from `getTCData` should match string used in `TCString.decode`.

**Actual behavior**
`TCData.tcString` from `getTCData` does not match string used in `TCString.decode`.
Specifically language part of the string turned into 'EN'.

![tcstring-issue](https://user-images.githubusercontent.com/6456249/74002075-d7148100-49a8-11ea-909a-a877b9f01ea6.gif)

**Comment by chrispaterson** [comment]
I see what is happening with this.  This is related to your #69 issue.  When the TCModel is created by decoding the string it sets the value correctly, but when 'getTCData' is called is has to go and get the versioned GVL to be able to encode the string again, when it does that the language from the GVL is overriding the previously set language.  I'll try to put in a patch for beta.8.
