### ISSUE TITLE
Polyfills for Symbol, Set are not added for IE 11 and responseType for JSON is not supported

### ISSUE THREAD

**Issue by mghouse036** [InteractiveAdvertisingBureau/iabtcf-es#76]
**Version**
1.0.0-beta.7

**Module**
 cmpapi and core

**Describe the bug**
1. With the latest update still facing same issue 'Symbol'. I think previous fix of lib config in tsconfig wont add any pollyfills it just wont complain ES5 syntax. We need use transpiler for this

Please find below screen shot
![image](https://user-images.githubusercontent.com/26306579/74308117-5cbf7480-4d8d-11ea-9342-61df38b13b29.png)

2. Set is partially supported in IE. It doesn't iterator syntax like new Set([1,2,3]) and add method is not supported.
![image](https://user-images.githubusercontent.com/26306579/74308440-3f3eda80-4d8e-11ea-87ef-c17675491c14.png)

3. Response type won't available in IE 11 (JSON.js in core)
![image](https://user-images.githubusercontent.com/26306579/74308860-5d590a80-4d8f-11ea-9e78-e9e9c94f53df.png)

**Comment by mghouse036** [comment]
@chrispaterson Any update on this issue

**Comment by chrispaterson** [comment]
I think using 'fetch' as issue #92 suggests we should do might fix this

**Comment by chrispaterson** [comment]
I'll try to spend some time on this today... I've been swamped, sorry for the delay

**Comment by chrispaterson** [comment]
After investigating, I think it's better if you add your own polyfills for whatever browser environment you are targeting.
