### ISSUE TITLE
tcfPolicyVersion and gvlSpecificationVersion are deleted after language is changed.

### ISSUE THREAD

**Issue by jgalisteo** [InteractiveAdvertisingBureau/iabtcf-es#77]
**Version**
1.0.0-beta.7

**Module**
core

**Describe the bug**
`tcfPolicyVersion` and `gvlSpecificationVersion` are being removed from GVL instance when another language is chosen.

**Steps to Reproduce**
```js
import {GVL} from '@iabtcf/core';

GVL.baseUrl = 'http://cmp.mysupercoolcmp.com/';

const gvl = new GVL();

await gvl.readyPromise;

await gvl.changeLanguage('es');
```

**Expected behavior**
`tcfPolicyVersion` and `gvlSpecificationVersion` should have the values that are present in
`vendor-list.json`.

**Actual behavior**
`tcfPolicyVersion` and `gvlSpecificationVersion` are `undefined` after the language is changed.

This is happening because the translations recently [published by IAB](https://register.consensu.org/Translation) does not contain any of these keys.

**Comment by nejcsever** [comment]
Hey @chrispaterson 
This issue still remains in my case. Here's the code snippet that proves that (I'm using version **1.0.0-beta.18**):
```
GVL.baseUrl = "https://your-api-hostname/vendor-list";
let gvl = new GVL();
gvl.readyPromise.then(() => {
    let defaultGVL = Object.assign({}, gvl);
    gvl.changeLanguage('es').finally(() => {
        console.log(`Default GVL tcfPolicyVersion: ${defaultGVL.tcfPolicyVersion}`);
        console.log(`Translated GVL tcfPolicyVersion: ${gvl.tcfPolicyVersion}`);
        console.log(`Default GVL gvlSpecificationVersion: ${defaultGVL.gvlSpecificationVersion}`);
        console.log(`Translated GVL gvlSpecificationVersion: ${gvl.gvlSpecificationVersion}`);
    });
});
```

**Should output:**
```
Default GVL tcfPolicyVersion: 2
init.js:37 Translated GVL tcfPolicyVersion: 2
init.js:38 Default GVL gvlSpecificationVersion: 2
init.js:39 Translated GVL gvlSpecificationVersion: 2
```
**Outputs:**
```
Default GVL tcfPolicyVersion: 2
init.js:37 Translated GVL tcfPolicyVersion: undefined
init.js:38 Default GVL gvlSpecificationVersion: 2
init.js:39 Translated GVL gvlSpecificationVersion: undefined
```

Am I missing something here?
