### ISSUE TITLE
Source maps throw warnings when compiling

### ISSUE THREAD

**Issue by trymedo** [InteractiveAdvertisingBureau/iabtcf-es#89]
**Version**
Which version does this occur on?
1.0.0-beta.13

**Module**
Is it core, cmpapi, cli, stub, or testing?
core

**Describe the bug**
A clear description of what the bug is.
when trying to build my cmp project, I get a lot of warnings about not being able to locate the src .ts files referenced in the .map file.

**Steps to Reproduce**
included the core package with 
`npm install @iabtcf/core --save`

included the core code:
`import {TCModel, TCString, GVL} from '@iabtcf/core';`

and then tried to compile my script with `npm run watch` or `npm run build`

**Expected behavior**
A clear description of what you expected to happen.
Compiling without warnings

**Actual behavior**
A clear description of what happened that was not expected.
Compiles with warnings

**Comment by trymedo** [comment]
![image (1)](https://user-images.githubusercontent.com/4124166/75559003-986b6700-5a3a-11ea-8205-eddae26529b8.png)

**Comment by chrispaterson** [comment]
I think I need to know a little more about your project set up:

What are you using to build?
What language?
Why do you think it has to do with source maps?
