### ISSUE TITLE
Purpose restrictions are not properly encoded

### ISSUE THREAD

**Issue by nealrosen04** [InteractiveAdvertisingBureau/iabtcf-es#90]
**Version**
Which version does this occur on?
1.0.0-beta.13

**Module**
Is it core, cmpapi, cli, stub, or testing?
core

**Describe the bug**
A clear description of what the bug is.
Purpose restrictions are not encoded properly.  There appears to be a bug in the logic that adds the relevant bits.  Specifically, this is in PurposeRestrictionVectorEncoder.encode().  There is a check for "!prVector.isEncodable()" before the encoding is performed.  I believe this is incorrectly negated and should be "prVector.isEncodable()".

Hacking in my debugger, I bypassed the !prVector.isEncodable() check and the restrictions appeared as expected.

**Steps to Reproduce**
Set a publisher restriction and encode the TCString.  Then decode that TCString. The publisher restriction does not appear.  

**Expected behavior**
A clear description of what you expected to happen.
The publisher restriction should be properly encoded

**Actual behavior**
A clear description of what happened that was not expected.
Only the numRestrictions is set.  The details about the restrictions are not encoded.

**Comment by nealrosen04** [comment]
Looks like this broke in commit 12912ca406

The condition changed from 
if (!value.isEmpty()) 
to
if (!prVector.isEncodable())

Perhaps the exclamation point was left behind inadvertently

**Comment by chrispaterson** [comment]
Goops, good catch... thank you
