### ISSUE TITLE
TCString.encode use 0 as vendorListVersion instead of gvl's

### ISSUE THREAD

**Issue by NLopezMad** [InteractiveAdvertisingBureau/iabtcf-es#91]
**Version**
1.0.0-beta.13

**Module**
core

**Describe the bug**
Decoding a string encoded with TCString.encode throw this error : "Error: invalid value 0 passed for vendorListVersion"

**Steps to Reproduce**
```javascript
import {GVL, TCString, TCModel} from '@iabtcf/core';
GVL.baseURL = "http://mydomain.com/cmp/vendorlist";
let gvl = new GVL("LATEST");
gvl.readyPromise.then(() => {
    const tcModel = new TCModel(gvl);
    tcModel.cmpId = CMPID;
    tcModel.cmpVersion = CMPVERSION;
    tcModel.consentScreen = CONSENTSCREEN;
    const encodedTCString = TCString.encode(tcModel);
    TCString.decode(encodedTCString);//Throw error
});
```

**Expected behavior**
TCString.encode should use gvl.vendorListVersion as vendorListVersion

**Actual behavior**
TCString.encode use 0 as vendorListVersion

**Comment by michael-sharethis** [comment]
a quick workaround until this is fixed is to set the vendorListVersion to whatever version you're supporting in the source code

**Comment by chrispaterson** [comment]
The first issue I see is that you are pointing to `BaseURL` instead of `BaseUrl`. So I think your GVL isn't loading.

**Comment by NLopezMad** [comment]
Sorry, I used baseUrl when testing but copied the example in @iabtcf/core TCString.encode to make a simplified example of how to reproduce the error when creating this issue.

Here is a corrected version which throw the error (tested with vendor list version 27) : 

```javascript 
import {GVL, TCString, TCModel} from '@iabtcf/core';
GVL.baseUrl = "http://mydomain.com/cmp/vendorlist";
GVL.latestFilename = 'vendor-list.json';
let gvl = new GVL("LATEST");
gvl.readyPromise.then(() => {
    const tcModel = new TCModel(gvl);
    tcModel.cmpId = CMPID;
    tcModel.cmpVersion = CMPVERSION;
    tcModel.consentScreen = CONSENTSCREEN;
    const encodedTCString = TCString.encode(tcModel);
    TCString.decode(encodedTCString);//Throw error
});
```

**Comment by chrispaterson** [comment]
Can you paste the Error also?

**Comment by NLopezMad** [comment]
Error: invalid value 0 passed for vendorListVersion

**Comment by kemalmustafic** [comment]
I have encountered the same issue. 

@NLopezMad as a temp fix, you could set **vendorListVersion** like this: ```tcModel.vendorListVersion_ = VENDOR_LIST_VERSION``` (note the `_` behind the **vendorListVersion**)

**Comment by Jofator** [comment]
The same issue with node using downloaded vendorList on local disk:
`const vendorList = require('./vendor-list');
const gvl = new GVL(vendorList)`
