### ISSUE TITLE
TC string is not properly decoded

### ISSUE THREAD

**Issue by mghouse036** [InteractiveAdvertisingBureau/iabtcf-es#95]
**Version**
1.0.0-beta.13

**Module**
core, cmpapi

**Describe the bug**
Not able to see the purpose when I decode below string using TCString.decode API

TC string given to decode:
`COv1p75Ov1p75AcABBENAcCMAP_AAAAAAAAAF0EWSQgAYWwho0QUBzBAIYAfJgSCAMgSAAQIoCkFQICERBAEKiAQHAEQJAAAGBAAkACAAQAoHCBMCQABgAARiRCEQECIDRNABIBAggAKYQFAAARmikHC3ZCY702yOmQAAAAA.IF0EWSQgAYWwho0QUBzBAIYAfJgSCAMgSAAQIoCkFQICERBAEKiAQHAEQJAAAGBAAkACAAQAoHCBMCQABgAARiRCEQECIDRNABIBAggAKYQFAAARmikHC3ZCY702yOmQ.YAAAAAAAAAAAAAAAAAA`

TC string return from cmp API:
`COv1rJlOv1rJlAcABBENAcCAAAAAAAAAAAAAAAAAAAAA.IF0EWSQgAYWwho0QUBzBAIYAfJgSCAMgSAAQIoCkFQICERBAEKiAQHAEQJAAAGBAAkACAAQAoHCBMCQABgAARiRCEQECIDRNABIBAggAKYQFAAARmikHC3ZCY702yOmQ.YAAAAAAAAAAAAAAAAAA`

![image](https://user-images.githubusercontent.com/26306579/76098005-ae56ca00-5fee-11ea-9124-ddb98ef663c6.png)

**Comment by chrispaterson** [comment]
I'm not sure I understand how to reproduce this issue.  I tried creating a test here.  Please look at https://github.com/InteractiveAdvertisingBureau/iabtcf-es/commit/b3e4db23e521a95f1ca2bc4a86252bf2ba06a0e9 this commit and tell me if I'm missing some steps

**Comment by mghouse036** [comment]
If I set CmpApiModel.tcModel twice, then __tcfapi is not returning the consent with latest TCModel

**Comment by chrispaterson** [comment]
Can you paste some code that reproduces this?
