### ISSUE TITLE
CMP does not respond to addEventListener when in error state

### ISSUE THREAD

**Issue by nealrosen04** [InteractiveAdvertisingBureau/iabtcf-es#96]
**Version**
Which version does this occur on?
1.0.0-beta.13

**Module**
Is it core, cmpapi, cli, stub, or testing?
cmpapi

**Describe the bug**
A clear description of what the bug is.
This is a bug in both the spec and the API.  The spec states that when the CMP enters an error state (cmpStatus = 'error'). the CMP will only respond to ping commands.  This poses a problem for callers.  They won't know when the CMP has entered this state.

**Steps to Reproduce**
Disable the CMP
Call the addEventListener command

**Expected behavior**
A clear description of what you expected to happen.
addEventListener callback should be called with the tcData.cmpStatus set to 'error'.

**Actual behavior**
A clear description of what happened that was not expected.
The callback is not called

**Comment by chrispaterson** [comment]
Thanks @nealrosen04
